# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_exception_list/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityExceptionList
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_exception_list,
      attributes_class: Elasticstack::Types::KibanaSecurityExceptionListAttributes,
      outputs: { id: :id },
      map: [:description, :name, :type],
      map_present: [:meta, :os_types, :tags]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityExceptionList
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
