# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaSecurityExceptionListAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :description, T::String
    attribute :name, T::String
    attribute :type, T::String
    attribute? :meta, T::String.optional
    attribute? :os_types, T::Array.of(T::String).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
