# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_import_saved_objects/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaImportSavedObjects
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_import_saved_objects,
      attributes_class: Elasticstack::Types::KibanaImportSavedObjectsAttributes,
      outputs: { id: :id },
      map: [:file_contents],
      map_present: [:space_id],
      map_bool: [:ignore_import_errors, :overwrite]
  end
  module Elasticstack
    include ElasticstackKibanaImportSavedObjects
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
