# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_index_lifecycle/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchIndexLifecycle
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_index_lifecycle,
      attributes_class: Elasticstack::Types::ElasticsearchIndexLifecycleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:cold, :delete, :elasticsearch_connection, :frozen, :hot, :metadata, :warm]
  end
  module Elasticstack
    include ElasticstackElasticsearchIndexLifecycle
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
