# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_security_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSecurityRole
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_security_role,
      attributes_class: Elasticstack::Types::ElasticsearchSecurityRoleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:applications, :cluster, :description, :elasticsearch_connection, :global, :indices, :remote_indices, :run_as]
  end
  module Elasticstack
    include ElasticstackElasticsearchSecurityRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
