# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchSecurityRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute? :applications, T::Array.of(T::Hash).optional
    attribute? :cluster, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :global, T::String.optional
    attribute? :indices, T::Array.of(T::Hash).optional
    attribute? :remote_indices, T::Array.of(T::Hash).optional
    attribute? :run_as, T::Array.of(T::String).optional
  end
end
