# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchMlDatafeedAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :datafeed_id, T::String
    attribute :indices, T::Array.of(T::String)
    attribute :job_id, T::String
    attribute? :aggregations, T::String.optional
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :max_empty_searches, T::Float.optional
    attribute? :runtime_mappings, T::String.optional
    attribute? :script_fields, T::String.optional
  end
end
