# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_index_alias/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchIndexAlias
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_index_alias,
      attributes_class: Elasticstack::Types::ElasticsearchIndexAliasAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:read_indices, :write_index]
  end
  module Elasticstack
    include ElasticstackElasticsearchIndexAlias
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
