# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchIndexAliasAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute? :read_indices, T::Array.of(T::Hash).optional
    attribute? :write_index, T::Hash.optional
  end
end
