# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_ml_job_state/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchMlJobState
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_ml_job_state,
      attributes_class: Elasticstack::Types::ElasticsearchMlJobStateAttributes,
      outputs: { id: :id },
      map: [:job_id, :state],
      map_present: [:elasticsearch_connection, :timeouts]
  end
  module Elasticstack
    include ElasticstackElasticsearchMlJobState
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
