# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_watch/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchWatch
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_watch,
      attributes_class: Elasticstack::Types::ElasticsearchWatchAttributes,
      outputs: { id: :id },
      map: [:trigger, :watch_id],
      map_present: [:actions, :condition, :input, :metadata, :throttle_period_in_millis, :transform],
      map_bool: [:active]
  end
  module Elasticstack
    include ElasticstackElasticsearchWatch
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
