# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchWatchAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :trigger, T::String
    attribute :watch_id, T::String
    attribute? :actions, T::String.optional
    attribute? :active, T::Bool.optional
    attribute? :condition, T::String.optional
    attribute? :input, T::String.optional
    attribute? :metadata, T::String.optional
    attribute? :throttle_period_in_millis, T::Float.optional
    attribute? :transform, T::String.optional
  end
end
