# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_enable_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityEnableRule
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_enable_rule,
      attributes_class: Elasticstack::Types::KibanaSecurityEnableRuleAttributes,
      outputs: { id: :id },
      map: [:key, :value]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityEnableRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
