# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_snapshot_lifecycle/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSnapshotLifecycle
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_snapshot_lifecycle,
      attributes_class: Elasticstack::Types::ElasticsearchSnapshotLifecycleAttributes,
      outputs: { id: :id },
      map: [:name, :repository, :schedule],
      map_present: [:elasticsearch_connection, :expand_wildcards, :expire_after, :max_count, :min_count, :snapshot_name],
      map_bool: [:ignore_unavailable, :include_global_state, :partial]
  end
  module Elasticstack
    include ElasticstackElasticsearchSnapshotLifecycle
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
