# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchSnapshotLifecycleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute :repository, T::String
    attribute :schedule, T::String
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :expand_wildcards, T::String.optional
    attribute? :expire_after, T::String.optional
    attribute? :ignore_unavailable, T::Bool.optional
    attribute? :include_global_state, T::Bool.optional
    attribute? :max_count, T::Float.optional
    attribute? :min_count, T::Float.optional
    attribute? :partial, T::Bool.optional
    attribute? :snapshot_name, T::String.optional
  end
end
