# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_apm_agent_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackApmAgentConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_apm_agent_configuration,
      attributes_class: Elasticstack::Types::ApmAgentConfigurationAttributes,
      outputs: { id: :id },
      map: [:service_name, :settings],
      map_present: [:agent_name, :service_environment]
  end
  module Elasticstack
    include ElasticstackApmAgentConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
