# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ApmAgentConfigurationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :service_name, T::String
    attribute :settings, T::Hash
    attribute? :agent_name, T::String.optional
    attribute? :service_environment, T::String.optional
  end
end
