# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_component_template/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchComponentTemplate
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_component_template,
      attributes_class: Elasticstack::Types::ElasticsearchComponentTemplateAttributes,
      outputs: { id: :id },
      map: [:name, :template],
      map_present: [:elasticsearch_connection, :metadata, :version]
  end
  module Elasticstack
    include ElasticstackElasticsearchComponentTemplate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
