# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchComponentTemplateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute :template, T::Array.of(T::Hash)
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :metadata, T::String.optional
    attribute? :version, T::Float.optional
  end
end
