# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_enrich_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchEnrichPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_enrich_policy,
      attributes_class: Elasticstack::Types::ElasticsearchEnrichPolicyAttributes,
      outputs: { id: :id },
      map: [:enrich_fields, :indices, :match_field, :name, :policy_type],
      map_present: [:elasticsearch_connection, :query]
  end
  module Elasticstack
    include ElasticstackElasticsearchEnrichPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
