# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchEnrichPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :enrich_fields, T::Array.of(T::String)
    attribute :indices, T::Array.of(T::String)
    attribute :match_field, T::String
    attribute :name, T::String
    attribute :policy_type, T::String
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :query, T::String.optional
  end
end
