# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_fleet_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackFleetIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_fleet_integration,
      attributes_class: Elasticstack::Types::FleetIntegrationAttributes,
      outputs: { id: :id },
      map: [:name, :version],
      map_bool: [:force, :ignore_constraints, :ignore_mapping_update_errors, :prerelease, :skip_data_stream_rollover, :skip_destroy]
  end
  module Elasticstack
    include ElasticstackFleetIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
