# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class FleetIntegrationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute :version, T::String
    attribute? :force, T::Bool.optional
    attribute? :ignore_constraints, T::Bool.optional
    attribute? :ignore_mapping_update_errors, T::Bool.optional
    attribute? :prerelease, T::Bool.optional
    attribute? :skip_data_stream_rollover, T::Bool.optional
    attribute? :skip_destroy, T::Bool.optional
  end
end
