# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_data_stream_lifecycle/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchDataStreamLifecycle
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_data_stream_lifecycle,
      attributes_class: Elasticstack::Types::ElasticsearchDataStreamLifecycleAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:data_retention, :downsampling, :elasticsearch_connection]
  end
  module Elasticstack
    include ElasticstackElasticsearchDataStreamLifecycle
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
