# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_space/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSpace
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_space,
      attributes_class: Elasticstack::Types::KibanaSpaceAttributes,
      outputs: { id: :id },
      map: [:name, :space_id],
      map_present: [:description, :image_url]
  end
  module Elasticstack
    include ElasticstackKibanaSpace
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
