# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaSpaceAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute :space_id, T::String
    attribute? :description, T::String.optional
    attribute? :image_url, T::String.optional
  end
end
