# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_index_template_ilm_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchIndexTemplateIlmAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_index_template_ilm_attachment,
      attributes_class: Elasticstack::Types::ElasticsearchIndexTemplateIlmAttachmentAttributes,
      outputs: { id: :id },
      map: [:index_template, :lifecycle_name]
  end
  module Elasticstack
    include ElasticstackElasticsearchIndexTemplateIlmAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
