# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_data_stream/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchDataStream
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_data_stream,
      attributes_class: Elasticstack::Types::ElasticsearchDataStreamAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:elasticsearch_connection]
  end
  module Elasticstack
    include ElasticstackElasticsearchDataStream
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
