# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaSyntheticsPrivateLocationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :agent_policy_id, T::String
    attribute :label, T::String
    attribute? :geo, T::Hash.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
