# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_security_system_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSecuritySystemUser
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_security_system_user,
      attributes_class: Elasticstack::Types::ElasticsearchSecuritySystemUserAttributes,
      outputs: { id: :id },
      map: [:username],
      map_present: [:elasticsearch_connection, :password, :password_hash]
  end
  module Elasticstack
    include ElasticstackElasticsearchSecuritySystemUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
