# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_logstash_pipeline/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchLogstashPipeline
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_logstash_pipeline,
      attributes_class: Elasticstack::Types::ElasticsearchLogstashPipelineAttributes,
      outputs: { id: :id },
      map: [:pipeline, :pipeline_id],
      map_present: [:description, :elasticsearch_connection, :pipeline_batch_delay, :pipeline_batch_size, :pipeline_ecs_compatibility, :pipeline_metadata, :pipeline_ordered, :pipeline_workers, :queue_checkpoint_acks, :queue_checkpoint_writes, :queue_max_bytes, :queue_max_events, :queue_page_capacity, :queue_type, :username],
      map_bool: [:pipeline_plugin_classloaders, :pipeline_unsafe_shutdown, :queue_checkpoint_retry, :queue_drain]
  end
  module Elasticstack
    include ElasticstackElasticsearchLogstashPipeline
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
