# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchLogstashPipelineAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :pipeline, T::String
    attribute :pipeline_id, T::String
    attribute? :description, T::String.optional
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :pipeline_batch_delay, T::Float.optional
    attribute? :pipeline_batch_size, T::Float.optional
    attribute? :pipeline_ecs_compatibility, T::String.optional
    attribute? :pipeline_metadata, T::String.optional
    attribute? :pipeline_ordered, T::String.optional
    attribute? :pipeline_plugin_classloaders, T::Bool.optional
    attribute? :pipeline_unsafe_shutdown, T::Bool.optional
    attribute? :pipeline_workers, T::Float.optional
    attribute? :queue_checkpoint_acks, T::Float.optional
    attribute? :queue_checkpoint_retry, T::Bool.optional
    attribute? :queue_checkpoint_writes, T::Float.optional
    attribute? :queue_drain, T::Bool.optional
    attribute? :queue_max_bytes, T::String.optional
    attribute? :queue_max_events, T::Float.optional
    attribute? :queue_page_capacity, T::String.optional
    attribute? :queue_type, T::String.optional
    attribute? :username, T::String.optional
  end
end
