# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_ml_anomaly_detection_job/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchMlAnomalyDetectionJob
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_ml_anomaly_detection_job,
      attributes_class: Elasticstack::Types::ElasticsearchMlAnomalyDetectionJobAttributes,
      outputs: { id: :id },
      map: [:analysis_config, :data_description, :job_id],
      map_present: [:background_persist_interval, :custom_settings, :description, :elasticsearch_connection, :groups, :model_plot_config, :renormalization_window_days, :results_retention_days]
  end
  module Elasticstack
    include ElasticstackElasticsearchMlAnomalyDetectionJob
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
