# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchMlAnomalyDetectionJobAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :analysis_config, T::Hash
    attribute :data_description, T::Hash
    attribute :job_id, T::String
    attribute? :background_persist_interval, T::String.optional
    attribute? :custom_settings, T::String.optional
    attribute? :description, T::String.optional
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :groups, T::Array.of(T::String).optional
    attribute? :model_plot_config, T::Hash.optional
    attribute? :renormalization_window_days, T::Float.optional
    attribute? :results_retention_days, T::Float.optional
  end
end
