# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_slo/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSlo
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_slo,
      attributes_class: Elasticstack::Types::KibanaSloAttributes,
      outputs: { id: :id },
      map: [:budgeting_method, :description, :name],
      map_present: [:apm_availability_indicator, :apm_latency_indicator, :histogram_custom_indicator, :kql_custom_indicator, :metric_custom_indicator, :objective, :settings, :tags, :time_window, :timeslice_metric_indicator]
  end
  module Elasticstack
    include ElasticstackKibanaSlo
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
