# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaSloAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :budgeting_method, T::String
    attribute :description, T::String
    attribute :name, T::String
    attribute? :apm_availability_indicator, T::Array.of(T::Hash).optional
    attribute? :apm_latency_indicator, T::Array.of(T::Hash).optional
    attribute? :histogram_custom_indicator, T::Array.of(T::Hash).optional
    attribute? :kql_custom_indicator, T::Array.of(T::Hash).optional
    attribute? :metric_custom_indicator, T::Array.of(T::Hash).optional
    attribute? :objective, T::Array.of(T::Hash).optional
    attribute? :settings, T::Hash.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :time_window, T::Array.of(T::Hash).optional
    attribute? :timeslice_metric_indicator, T::Array.of(T::Hash).optional
  end
end
