# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_detection_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityDetectionRule
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_detection_rule,
      attributes_class: Elasticstack::Types::KibanaSecurityDetectionRuleAttributes,
      outputs: { id: :id },
      map: [:description, :name, :type],
      map_present: [:actions, :alert_suppression, :anomaly_threshold, :building_block_type, :concurrent_searches, :data_view_id, :exceptions_list, :filters, :history_window_start, :investigation_fields, :items_per_search, :license, :machine_learning_job_id, :namespace, :new_terms_fields, :note, :related_integrations, :required_fields, :response_actions, :risk_score_mapping, :rule_name_override, :saved_id, :setup, :severity_mapping, :threat, :threat_filters, :threat_index, :threat_mapping, :threshold, :tiebreaker_field, :timeline_id, :timeline_title, :timestamp_override],
      map_bool: [:timestamp_override_fallback_disabled]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityDetectionRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
