# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaSecurityDetectionRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :description, T::String
    attribute :name, T::String
    attribute :type, T::String
    attribute? :actions, T::Array.of(T::Hash).optional
    attribute? :alert_suppression, T::Hash.optional
    attribute? :anomaly_threshold, T::Float.optional
    attribute? :building_block_type, T::String.optional
    attribute? :concurrent_searches, T::Float.optional
    attribute? :data_view_id, T::String.optional
    attribute? :exceptions_list, T::Array.of(T::Hash).optional
    attribute? :filters, T::String.optional
    attribute? :history_window_start, T::String.optional
    attribute? :investigation_fields, T::Array.of(T::String).optional
    attribute? :items_per_search, T::Float.optional
    attribute? :license, T::String.optional
    attribute? :machine_learning_job_id, T::Array.of(T::String).optional
    attribute? :namespace, T::String.optional
    attribute? :new_terms_fields, T::Array.of(T::String).optional
    attribute? :note, T::String.optional
    attribute? :related_integrations, T::Array.of(T::Hash).optional
    attribute? :required_fields, T::Array.of(T::Hash).optional
    attribute? :response_actions, T::Array.of(T::Hash).optional
    attribute? :risk_score_mapping, T::Array.of(T::Hash).optional
    attribute? :rule_name_override, T::String.optional
    attribute? :saved_id, T::String.optional
    attribute? :setup, T::String.optional
    attribute? :severity_mapping, T::Array.of(T::Hash).optional
    attribute? :threat, T::Array.of(T::Hash).optional
    attribute? :threat_filters, T::Array.of(T::String).optional
    attribute? :threat_index, T::Array.of(T::String).optional
    attribute? :threat_mapping, T::Array.of(T::Hash).optional
    attribute? :threshold, T::Hash.optional
    attribute? :tiebreaker_field, T::String.optional
    attribute? :timeline_id, T::String.optional
    attribute? :timeline_title, T::String.optional
    attribute? :timestamp_override, T::String.optional
    attribute? :timestamp_override_fallback_disabled, T::Bool.optional
  end
end
