# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_exception_item/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityExceptionItem
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_exception_item,
      attributes_class: Elasticstack::Types::KibanaSecurityExceptionItemAttributes,
      outputs: { id: :id },
      map: [:description, :entries, :list_id, :name, :type],
      map_present: [:comments, :meta, :os_types, :tags]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityExceptionItem
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
