# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_install_prebuilt_rules/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaInstallPrebuiltRules
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_install_prebuilt_rules,
      attributes_class: Elasticstack::Types::KibanaInstallPrebuiltRulesAttributes,
      outputs: { id: :id }
  end
  module Elasticstack
    include ElasticstackKibanaInstallPrebuiltRules
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
