# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_index_template/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchIndexTemplate
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_index_template,
      attributes_class: Elasticstack::Types::ElasticsearchIndexTemplateAttributes,
      outputs: { id: :id },
      map: [:index_patterns, :name],
      map_present: [:data_stream, :elasticsearch_connection, :metadata, :priority, :template, :version]
  end
  module Elasticstack
    include ElasticstackElasticsearchIndexTemplate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
