# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_alerting_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaAlertingRule
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_alerting_rule,
      attributes_class: Elasticstack::Types::KibanaAlertingRuleAttributes,
      outputs: { id: :id },
      map: [:consumer, :interval, :name, :params, :rule_type_id],
      map_present: [:actions, :tags, :throttle]
  end
  module Elasticstack
    include ElasticstackKibanaAlertingRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
