# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaAlertingRuleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :consumer, T::String
    attribute :interval, T::String
    attribute :name, T::String
    attribute :params, T::String
    attribute :rule_type_id, T::String
    attribute? :actions, T::Array.of(T::Hash).optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :throttle, T::String.optional
  end
end
