# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_fleet_output/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackFleetOutput
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_fleet_output,
      attributes_class: Elasticstack::Types::FleetOutputAttributes,
      outputs: { id: :id },
      map: [:hosts, :name, :type],
      map_present: [:ca_sha256, :ca_trusted_fingerprint, :config_yaml, :kafka, :ssl]
  end
  module Elasticstack
    include ElasticstackFleetOutput
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
