# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_security_api_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSecurityApiKey
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_security_api_key,
      attributes_class: Elasticstack::Types::ElasticsearchSecurityApiKeyAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:access, :elasticsearch_connection, :expiration]
  end
  module Elasticstack
    include ElasticstackElasticsearchSecurityApiKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
