# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_default_data_view/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaDefaultDataView
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_default_data_view,
      attributes_class: Elasticstack::Types::KibanaDefaultDataViewAttributes,
      outputs: { id: :id },
      map_present: [:data_view_id],
      map_bool: [:force]
  end
  module Elasticstack
    include ElasticstackKibanaDefaultDataView
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
