# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityRole
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_role,
      attributes_class: Elasticstack::Types::KibanaSecurityRoleAttributes,
      outputs: { id: :id },
      map: [:elasticsearch, :name],
      map_present: [:description, :kibana]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
