# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_fleet_agent_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackFleetAgentPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_fleet_agent_policy,
      attributes_class: Elasticstack::Types::FleetAgentPolicyAttributes,
      outputs: { id: :id },
      map: [:name, :namespace],
      map_present: [:data_output_id, :description, :download_source_id, :fleet_server_host_id, :monitoring_output_id],
      map_bool: [:skip_destroy, :supports_agentless, :sys_monitoring]
  end
  module Elasticstack
    include ElasticstackFleetAgentPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
