# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class FleetAgentPolicyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute :namespace, T::String
    attribute? :data_output_id, T::String.optional
    attribute? :description, T::String.optional
    attribute? :download_source_id, T::String.optional
    attribute? :fleet_server_host_id, T::String.optional
    attribute? :monitoring_output_id, T::String.optional
    attribute? :skip_destroy, T::Bool.optional
    attribute? :supports_agentless, T::Bool.optional
    attribute? :sys_monitoring, T::Bool.optional
  end
end
