# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_security_role_mapping/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSecurityRoleMapping
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_security_role_mapping,
      attributes_class: Elasticstack::Types::ElasticsearchSecurityRoleMappingAttributes,
      outputs: { id: :id },
      map: [:name, :rules],
      map_present: [:elasticsearch_connection, :role_templates, :roles]
  end
  module Elasticstack
    include ElasticstackElasticsearchSecurityRoleMapping
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
