# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchSecurityRoleMappingAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :name, T::String
    attribute :rules, T::String
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :role_templates, T::String.optional
    attribute? :roles, T::Array.of(T::String).optional
  end
end
