# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_ml_datafeed_state/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchMlDatafeedState
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_ml_datafeed_state,
      attributes_class: Elasticstack::Types::ElasticsearchMlDatafeedStateAttributes,
      outputs: { id: :id },
      map: [:datafeed_id, :state],
      map_present: [:elasticsearch_connection, :end, :timeouts]
  end
  module Elasticstack
    include ElasticstackElasticsearchMlDatafeedState
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
