# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchMlDatafeedStateAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :datafeed_id, T::String
    attribute :state, T::String
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :end, T::String.optional
    attribute? :timeouts, T::Hash.optional
  end
end
