# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_snapshot_repository/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSnapshotRepository
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_snapshot_repository,
      attributes_class: Elasticstack::Types::ElasticsearchSnapshotRepositoryAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:azure, :elasticsearch_connection, :fs, :gcs, :hdfs, :s3, :url],
      map_bool: [:verify]
  end
  module Elasticstack
    include ElasticstackElasticsearchSnapshotRepository
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
