# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_action_connector/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaActionConnector
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_action_connector,
      attributes_class: Elasticstack::Types::KibanaActionConnectorAttributes,
      outputs: { id: :id },
      map: [:connector_type_id, :name],
      map_present: [:kibana_connection, :secrets]
  end
  module Elasticstack
    include ElasticstackKibanaActionConnector
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
