# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaActionConnectorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :connector_type_id, T::String
    attribute :name, T::String
    attribute? :kibana_connection, T::Array.of(T::Hash).optional
    attribute? :secrets, T::String.optional
  end
end
