# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_list/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityList
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_list,
      attributes_class: Elasticstack::Types::KibanaSecurityListAttributes,
      outputs: { id: :id },
      map: [:description, :name, :type],
      map_present: [:meta]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityList
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
