# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_script/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchScript
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_script,
      attributes_class: Elasticstack::Types::ElasticsearchScriptAttributes,
      outputs: { id: :id },
      map: [:lang, :script_id, :source],
      map_present: [:context, :elasticsearch_connection, :params]
  end
  module Elasticstack
    include ElasticstackElasticsearchScript
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
