# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchScriptAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :lang, T::String
    attribute :script_id, T::String
    attribute :source, T::String
    attribute? :context, T::String.optional
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :params, T::String.optional
  end
end
