# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_kibana_security_list_item/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackKibanaSecurityListItem
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_kibana_security_list_item,
      attributes_class: Elasticstack::Types::KibanaSecurityListItemAttributes,
      outputs: { id: :id },
      map: [:list_id, :value],
      map_present: [:meta]
  end
  module Elasticstack
    include ElasticstackKibanaSecurityListItem
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
