# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class KibanaSecurityListItemAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :list_id, T::String
    attribute :value, T::String
    attribute? :meta, T::String.optional
  end
end
