# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_security_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchSecurityRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':elasticstack_elasticsearch_security_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_security_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_role('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_security_role.test.id}")
        expect(ref.metadata).to eq("${elasticstack_elasticsearch_security_role.test.metadata}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'test')
        expect(config).not_to have_key('metadata')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ applications: [{ 'key1' => 'val1' }], cluster: ['test-value'], description: 'test-value', elasticsearch_connection: [{ 'key1' => 'val1' }], global: 'test-value', indices: [{ 'key1' => 'val1' }], remote_indices: [{ 'key1' => 'val1' }], run_as: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'full')
        expect(config).to have_key('applications')
        expect(config).to have_key('cluster')
        expect(config).to have_key('description')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('global')
        expect(config).to have_key('indices')
        expect(config).to have_key('remote_indices')
        expect(config).to have_key('run_as')
      end
    end

    context 'optional attributes' do
      it 'includes applications when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(applications: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('applications')
      end

      it 'omits applications when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('applications')
      end
      it 'includes cluster when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(cluster: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('cluster')
      end

      it 'omits cluster when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('cluster')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes global when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(global: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('global')
      end

      it 'omits global when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('global')
      end
      it 'includes indices when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(indices: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('indices')
      end

      it 'omits indices when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('indices')
      end
      it 'includes remote_indices when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(remote_indices: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('remote_indices')
      end

      it 'omits remote_indices when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('remote_indices')
      end
      it 'includes run_as when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('opt', required_attrs.merge(run_as: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'opt')
        expect(config).to have_key('run_as')
      end

      it 'omits run_as when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'minimal')
        expect(config).not_to have_key('run_as')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role('first', required_attrs)
        synth.elasticstack_elasticsearch_security_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_security_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_security_role,
    method: :elasticstack_elasticsearch_security_role,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :metadata],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
