# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_index_lifecycle resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchIndexLifecycle do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':elasticstack_elasticsearch_index_lifecycle' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_index_lifecycle('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_index_lifecycle)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_index_lifecycle('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_index_lifecycle.test.id}")
        expect(ref.modified_date).to eq("${elasticstack_elasticsearch_index_lifecycle.test.modified_date}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'test')
        expect(config).not_to have_key('modified_date')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cold: [{ 'key1' => 'val1' }], delete: [{ 'key1' => 'val1' }], elasticsearch_connection: [{ 'key1' => 'val1' }], frozen: [{ 'key1' => 'val1' }], hot: [{ 'key1' => 'val1' }], metadata: 'test-value', warm: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'full')
        expect(config).to have_key('cold')
        expect(config).to have_key('delete')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('frozen')
        expect(config).to have_key('hot')
        expect(config).to have_key('metadata')
        expect(config).to have_key('warm')
      end
    end

    context 'optional attributes' do
      it 'includes cold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(cold: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('cold')
      end

      it 'omits cold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('cold')
      end
      it 'includes delete when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(delete: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('delete')
      end

      it 'omits delete when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('delete')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes frozen when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(frozen: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('frozen')
      end

      it 'omits frozen when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('frozen')
      end
      it 'includes hot when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(hot: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('hot')
      end

      it 'omits hot when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('hot')
      end
      it 'includes metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(metadata: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('metadata')
      end

      it 'omits metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('metadata')
      end
      it 'includes warm when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('opt', required_attrs.merge(warm: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'opt')
        expect(config).to have_key('warm')
      end

      it 'omits warm when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'minimal')
        expect(config).not_to have_key('warm')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_lifecycle', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_lifecycle('first', required_attrs)
        synth.elasticstack_elasticsearch_index_lifecycle('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_index_lifecycle')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_index_lifecycle,
    method: :elasticstack_elasticsearch_index_lifecycle,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :modified_date],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
