# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_space resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaSpace do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', space_id: 'test-value' } }

  describe ':elasticstack_kibana_space' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'test')
        validate_required_attributes(config, [:name, :space_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_space('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_space)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_space('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_space.test.id}")
        expect(ref.color).to eq("${elasticstack_kibana_space.test.color}")
        expect(ref.disabled_features).to eq("${elasticstack_kibana_space.test.disabled_features}")
        expect(ref.initials).to eq("${elasticstack_kibana_space.test.initials}")
        expect(ref.solution).to eq("${elasticstack_kibana_space.test.solution}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'test')
        expect(config).not_to have_key('color')
        expect(config).not_to have_key('disabled_features')
        expect(config).not_to have_key('initials')
        expect(config).not_to have_key('solution')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', image_url: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('image_url')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes image_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('opt', required_attrs.merge(image_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'opt')
        expect(config).to have_key('image_url')
      end

      it 'omits image_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'minimal')
        expect(config).not_to have_key('image_url')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_space', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['space_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_space('first', required_attrs)
        synth.elasticstack_kibana_space('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_space')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_space,
    method: :elasticstack_kibana_space,
    required_attrs: { name: 'test-value', space_id: 'test-value' },
    expected_outputs: [:id, :color, :disabled_features, :initials, :solution],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
