# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_ml_datafeed resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchMlDatafeed do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { datafeed_id: 'test-value', indices: ['test-value'], job_id: 'test-value' } }

  describe ':elasticstack_elasticsearch_ml_datafeed' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'test')
        validate_required_attributes(config, [:datafeed_id, :indices, :job_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_ml_datafeed('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_ml_datafeed)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_ml_datafeed('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_ml_datafeed.test.id}")
        expect(ref.chunking_config).to eq("${elasticstack_elasticsearch_ml_datafeed.test.chunking_config}")
        expect(ref.delayed_data_check_config).to eq("${elasticstack_elasticsearch_ml_datafeed.test.delayed_data_check_config}")
        expect(ref.frequency).to eq("${elasticstack_elasticsearch_ml_datafeed.test.frequency}")
        expect(ref.indices_options).to eq("${elasticstack_elasticsearch_ml_datafeed.test.indices_options}")
        expect(ref.query).to eq("${elasticstack_elasticsearch_ml_datafeed.test.query}")
        expect(ref.query_delay).to eq("${elasticstack_elasticsearch_ml_datafeed.test.query_delay}")
        expect(ref.scroll_size).to eq("${elasticstack_elasticsearch_ml_datafeed.test.scroll_size}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'test')
        expect(config).not_to have_key('chunking_config')
        expect(config).not_to have_key('delayed_data_check_config')
        expect(config).not_to have_key('frequency')
        expect(config).not_to have_key('indices_options')
        expect(config).not_to have_key('query')
        expect(config).not_to have_key('query_delay')
        expect(config).not_to have_key('scroll_size')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ aggregations: 'test-value', elasticsearch_connection: [{ 'key1' => 'val1' }], max_empty_searches: 3.14, runtime_mappings: 'test-value', script_fields: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'full')
        expect(config).to have_key('aggregations')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('max_empty_searches')
        expect(config).to have_key('runtime_mappings')
        expect(config).to have_key('script_fields')
      end
    end

    context 'optional attributes' do
      it 'includes aggregations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('opt', required_attrs.merge(aggregations: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'opt')
        expect(config).to have_key('aggregations')
      end

      it 'omits aggregations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'minimal')
        expect(config).not_to have_key('aggregations')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes max_empty_searches when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('opt', required_attrs.merge(max_empty_searches: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'opt')
        expect(config).to have_key('max_empty_searches')
      end

      it 'omits max_empty_searches when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'minimal')
        expect(config).not_to have_key('max_empty_searches')
      end
      it 'includes runtime_mappings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('opt', required_attrs.merge(runtime_mappings: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'opt')
        expect(config).to have_key('runtime_mappings')
      end

      it 'omits runtime_mappings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'minimal')
        expect(config).not_to have_key('runtime_mappings')
      end
      it 'includes script_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('opt', required_attrs.merge(script_fields: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'opt')
        expect(config).to have_key('script_fields')
      end

      it 'omits script_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'minimal')
        expect(config).not_to have_key('script_fields')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed', 'typed')
        expect(config['datafeed_id']).to be_a(String)
        expect(config['indices']).to be_a(Array)
        expect(config['job_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed('first', required_attrs)
        synth.elasticstack_elasticsearch_ml_datafeed('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_ml_datafeed')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_ml_datafeed,
    method: :elasticstack_elasticsearch_ml_datafeed,
    required_attrs: { datafeed_id: 'test-value', indices: ['test-value'], job_id: 'test-value' },
    expected_outputs: [:id, :chunking_config, :delayed_data_check_config, :frequency, :indices_options, :query, :query_delay, :scroll_size],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
