# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_index_template resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchIndexTemplate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { index_patterns: ['test-value'], name: 'test-value' } }

  describe ':elasticstack_elasticsearch_index_template' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'test')
        validate_required_attributes(config, [:index_patterns, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_index_template('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_index_template)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_index_template('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_index_template.test.id}")
        expect(ref.composed_of).to eq("${elasticstack_elasticsearch_index_template.test.composed_of}")
        expect(ref.ignore_missing_component_templates).to eq("${elasticstack_elasticsearch_index_template.test.ignore_missing_component_templates}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'test')
        expect(config).not_to have_key('composed_of')
        expect(config).not_to have_key('ignore_missing_component_templates')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_stream: [{ 'key1' => 'val1' }], elasticsearch_connection: [{ 'key1' => 'val1' }], metadata: 'test-value', priority: 3.14, template: [{ 'key1' => 'val1' }], version: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'full')
        expect(config).to have_key('data_stream')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('metadata')
        expect(config).to have_key('priority')
        expect(config).to have_key('template')
        expect(config).to have_key('version')
      end
    end

    context 'optional attributes' do
      it 'includes data_stream when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('opt', required_attrs.merge(data_stream: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'opt')
        expect(config).to have_key('data_stream')
      end

      it 'omits data_stream when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'minimal')
        expect(config).not_to have_key('data_stream')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('opt', required_attrs.merge(metadata: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'opt')
        expect(config).to have_key('metadata')
      end

      it 'omits metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'minimal')
        expect(config).not_to have_key('metadata')
      end
      it 'includes priority when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('opt', required_attrs.merge(priority: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'opt')
        expect(config).to have_key('priority')
      end

      it 'omits priority when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'minimal')
        expect(config).not_to have_key('priority')
      end
      it 'includes template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('opt', required_attrs.merge(template: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'opt')
        expect(config).to have_key('template')
      end

      it 'omits template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'minimal')
        expect(config).not_to have_key('template')
      end
      it 'includes version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('opt', required_attrs.merge(version: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'opt')
        expect(config).to have_key('version')
      end

      it 'omits version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'minimal')
        expect(config).not_to have_key('version')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_index_template', 'typed')
        expect(config['index_patterns']).to be_a(Array)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_index_template('first', required_attrs)
        synth.elasticstack_elasticsearch_index_template('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_index_template')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_index_template,
    method: :elasticstack_elasticsearch_index_template,
    required_attrs: { index_patterns: ['test-value'], name: 'test-value' },
    expected_outputs: [:id, :composed_of, :ignore_missing_component_templates],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
