# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_logstash_pipeline resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchLogstashPipeline do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { pipeline: 'test-value', pipeline_id: 'test-value' } }

  describe ':elasticstack_elasticsearch_logstash_pipeline' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'test')
        validate_required_attributes(config, [:pipeline, :pipeline_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_logstash_pipeline('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_logstash_pipeline)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_logstash_pipeline('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_logstash_pipeline.test.id}")
        expect(ref.last_modified).to eq("${elasticstack_elasticsearch_logstash_pipeline.test.last_modified}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'test')
        expect(config).not_to have_key('last_modified')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', elasticsearch_connection: [{ 'key1' => 'val1' }], pipeline_batch_delay: 3.14, pipeline_batch_size: 3.14, pipeline_ecs_compatibility: 'test-value', pipeline_metadata: 'test-value', pipeline_ordered: 'test-value', pipeline_plugin_classloaders: true, pipeline_unsafe_shutdown: true, pipeline_workers: 3.14, queue_checkpoint_acks: 3.14, queue_checkpoint_retry: true, queue_checkpoint_writes: 3.14, queue_drain: true, queue_max_bytes: 'test-value', queue_max_events: 3.14, queue_page_capacity: 'test-value', queue_type: 'test-value', username: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('pipeline_batch_delay')
        expect(config).to have_key('pipeline_batch_size')
        expect(config).to have_key('pipeline_ecs_compatibility')
        expect(config).to have_key('pipeline_metadata')
        expect(config).to have_key('pipeline_ordered')
        expect(config).to have_key('pipeline_plugin_classloaders')
        expect(config).to have_key('pipeline_unsafe_shutdown')
        expect(config).to have_key('pipeline_workers')
        expect(config).to have_key('queue_checkpoint_acks')
        expect(config).to have_key('queue_checkpoint_retry')
        expect(config).to have_key('queue_checkpoint_writes')
        expect(config).to have_key('queue_drain')
        expect(config).to have_key('queue_max_bytes')
        expect(config).to have_key('queue_max_events')
        expect(config).to have_key('queue_page_capacity')
        expect(config).to have_key('queue_type')
        expect(config).to have_key('username')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes pipeline_batch_delay when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_batch_delay: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_batch_delay')
      end

      it 'omits pipeline_batch_delay when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_batch_delay')
      end
      it 'includes pipeline_batch_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_batch_size: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_batch_size')
      end

      it 'omits pipeline_batch_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_batch_size')
      end
      it 'includes pipeline_ecs_compatibility when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_ecs_compatibility: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_ecs_compatibility')
      end

      it 'omits pipeline_ecs_compatibility when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_ecs_compatibility')
      end
      it 'includes pipeline_metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_metadata: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_metadata')
      end

      it 'omits pipeline_metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_metadata')
      end
      it 'includes pipeline_ordered when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_ordered: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_ordered')
      end

      it 'omits pipeline_ordered when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_ordered')
      end
      it 'includes pipeline_plugin_classloaders when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_plugin_classloaders: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_plugin_classloaders')
      end

      it 'omits pipeline_plugin_classloaders when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_plugin_classloaders')
      end
      it 'includes pipeline_unsafe_shutdown when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_unsafe_shutdown: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_unsafe_shutdown')
      end

      it 'omits pipeline_unsafe_shutdown when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_unsafe_shutdown')
      end
      it 'includes pipeline_workers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(pipeline_workers: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('pipeline_workers')
      end

      it 'omits pipeline_workers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('pipeline_workers')
      end
      it 'includes queue_checkpoint_acks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_checkpoint_acks: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_checkpoint_acks')
      end

      it 'omits queue_checkpoint_acks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_checkpoint_acks')
      end
      it 'includes queue_checkpoint_retry when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_checkpoint_retry: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_checkpoint_retry')
      end

      it 'omits queue_checkpoint_retry when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_checkpoint_retry')
      end
      it 'includes queue_checkpoint_writes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_checkpoint_writes: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_checkpoint_writes')
      end

      it 'omits queue_checkpoint_writes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_checkpoint_writes')
      end
      it 'includes queue_drain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_drain: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_drain')
      end

      it 'omits queue_drain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_drain')
      end
      it 'includes queue_max_bytes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_max_bytes: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_max_bytes')
      end

      it 'omits queue_max_bytes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_max_bytes')
      end
      it 'includes queue_max_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_max_events: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_max_events')
      end

      it 'omits queue_max_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_max_events')
      end
      it 'includes queue_page_capacity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_page_capacity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_page_capacity')
      end

      it 'omits queue_page_capacity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_page_capacity')
      end
      it 'includes queue_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(queue_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('queue_type')
      end

      it 'omits queue_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('queue_type')
      end
      it 'includes username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('opt', required_attrs.merge(username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'opt')
        expect(config).to have_key('username')
      end

      it 'omits username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'minimal')
        expect(config).not_to have_key('username')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts pipeline_plugin_classloaders=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(pipeline_plugin_classloaders: val)
          synth.elasticstack_elasticsearch_logstash_pipeline("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', "bool_#{val}")
          expect(config['pipeline_plugin_classloaders']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts pipeline_unsafe_shutdown=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(pipeline_unsafe_shutdown: val)
          synth.elasticstack_elasticsearch_logstash_pipeline("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', "bool_#{val}")
          expect(config['pipeline_unsafe_shutdown']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts queue_checkpoint_retry=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(queue_checkpoint_retry: val)
          synth.elasticstack_elasticsearch_logstash_pipeline("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', "bool_#{val}")
          expect(config['queue_checkpoint_retry']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts queue_drain=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(queue_drain: val)
          synth.elasticstack_elasticsearch_logstash_pipeline("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', "bool_#{val}")
          expect(config['queue_drain']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_logstash_pipeline', 'typed')
        expect(config['pipeline']).to be_a(String)
        expect(config['pipeline_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_logstash_pipeline('first', required_attrs)
        synth.elasticstack_elasticsearch_logstash_pipeline('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_logstash_pipeline')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_logstash_pipeline,
    method: :elasticstack_elasticsearch_logstash_pipeline,
    required_attrs: { pipeline: 'test-value', pipeline_id: 'test-value' },
    expected_outputs: [:id, :last_modified],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:pipeline_plugin_classloaders, :pipeline_unsafe_shutdown, :queue_checkpoint_retry, :queue_drain]
end
