# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_default_data_view resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaDefaultDataView do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':elasticstack_kibana_default_data_view' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_default_data_view('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_default_data_view)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_default_data_view('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_default_data_view.test.id}")
        expect(ref.skip_delete).to eq("${elasticstack_kibana_default_data_view.test.skip_delete}")
        expect(ref.space_id).to eq("${elasticstack_kibana_default_data_view.test.space_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'test')
        expect(config).not_to have_key('skip_delete')
        expect(config).not_to have_key('space_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_view_id: 'test-value', force: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'full')
        expect(config).to have_key('data_view_id')
        expect(config).to have_key('force')
      end
    end

    context 'optional attributes' do
      it 'includes data_view_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('opt', required_attrs.merge(data_view_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'opt')
        expect(config).to have_key('data_view_id')
      end

      it 'omits data_view_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'minimal')
        expect(config).not_to have_key('data_view_id')
      end
      it 'includes force when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('opt', required_attrs.merge(force: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'opt')
        expect(config).to have_key('force')
      end

      it 'omits force when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'minimal')
        expect(config).not_to have_key('force')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force: val)
          synth.elasticstack_kibana_default_data_view("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', "bool_#{val}")
          expect(config['force']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_default_data_view', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_default_data_view('first', required_attrs)
        synth.elasticstack_kibana_default_data_view('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_default_data_view')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_default_data_view,
    method: :elasticstack_kibana_default_data_view,
    required_attrs: {},
    expected_outputs: [:id, :skip_delete, :space_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:force]
end
