# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_enrich_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchEnrichPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { enrich_fields: ['test-value'], indices: ['test-value'], match_field: 'test-value', name: 'test-value', policy_type: 'test-value' } }

  describe ':elasticstack_elasticsearch_enrich_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'test')
        validate_required_attributes(config, [:enrich_fields, :indices, :match_field, :name, :policy_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_enrich_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_enrich_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_enrich_policy('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_enrich_policy.test.id}")
        expect(ref.execute).to eq("${elasticstack_elasticsearch_enrich_policy.test.execute}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'test')
        expect(config).not_to have_key('execute')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ elasticsearch_connection: [{ 'key1' => 'val1' }], query: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'full')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('query')
      end
    end

    context 'optional attributes' do
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes query when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('opt', required_attrs.merge(query: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'opt')
        expect(config).to have_key('query')
      end

      it 'omits query when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'minimal')
        expect(config).not_to have_key('query')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_enrich_policy', 'typed')
        expect(config['enrich_fields']).to be_a(Array)
        expect(config['indices']).to be_a(Array)
        expect(config['match_field']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['policy_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_enrich_policy('first', required_attrs)
        synth.elasticstack_elasticsearch_enrich_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_enrich_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_enrich_policy,
    method: :elasticstack_elasticsearch_enrich_policy,
    required_attrs: { enrich_fields: ['test-value'], indices: ['test-value'], match_field: 'test-value', name: 'test-value', policy_type: 'test-value' },
    expected_outputs: [:id, :execute],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
