# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_slo resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaSlo do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { budgeting_method: 'test-value', description: 'test-value', name: 'test-value' } }

  describe ':elasticstack_kibana_slo' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'test')
        validate_required_attributes(config, [:budgeting_method, :description, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_slo('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_slo)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_slo('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_slo.test.id}")
        expect(ref.group_by).to eq("${elasticstack_kibana_slo.test.group_by}")
        expect(ref.slo_id).to eq("${elasticstack_kibana_slo.test.slo_id}")
        expect(ref.space_id).to eq("${elasticstack_kibana_slo.test.space_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'test')
        expect(config).not_to have_key('group_by')
        expect(config).not_to have_key('slo_id')
        expect(config).not_to have_key('space_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ apm_availability_indicator: [{ 'key1' => 'val1' }], apm_latency_indicator: [{ 'key1' => 'val1' }], histogram_custom_indicator: [{ 'key1' => 'val1' }], kql_custom_indicator: [{ 'key1' => 'val1' }], metric_custom_indicator: [{ 'key1' => 'val1' }], objective: [{ 'key1' => 'val1' }], settings: { 'key1' => 'val1' }, tags: ['test-value'], time_window: [{ 'key1' => 'val1' }], timeslice_metric_indicator: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'full')
        expect(config).to have_key('apm_availability_indicator')
        expect(config).to have_key('apm_latency_indicator')
        expect(config).to have_key('histogram_custom_indicator')
        expect(config).to have_key('kql_custom_indicator')
        expect(config).to have_key('metric_custom_indicator')
        expect(config).to have_key('objective')
        expect(config).to have_key('settings')
        expect(config).to have_key('tags')
        expect(config).to have_key('time_window')
        expect(config).to have_key('timeslice_metric_indicator')
      end
    end

    context 'optional attributes' do
      it 'includes apm_availability_indicator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(apm_availability_indicator: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('apm_availability_indicator')
      end

      it 'omits apm_availability_indicator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('apm_availability_indicator')
      end
      it 'includes apm_latency_indicator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(apm_latency_indicator: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('apm_latency_indicator')
      end

      it 'omits apm_latency_indicator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('apm_latency_indicator')
      end
      it 'includes histogram_custom_indicator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(histogram_custom_indicator: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('histogram_custom_indicator')
      end

      it 'omits histogram_custom_indicator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('histogram_custom_indicator')
      end
      it 'includes kql_custom_indicator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(kql_custom_indicator: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('kql_custom_indicator')
      end

      it 'omits kql_custom_indicator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('kql_custom_indicator')
      end
      it 'includes metric_custom_indicator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(metric_custom_indicator: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('metric_custom_indicator')
      end

      it 'omits metric_custom_indicator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('metric_custom_indicator')
      end
      it 'includes objective when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(objective: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('objective')
      end

      it 'omits objective when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('objective')
      end
      it 'includes settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(settings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('settings')
      end

      it 'omits settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('settings')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('tags')
      end
      it 'includes time_window when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(time_window: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('time_window')
      end

      it 'omits time_window when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('time_window')
      end
      it 'includes timeslice_metric_indicator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('opt', required_attrs.merge(timeslice_metric_indicator: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'opt')
        expect(config).to have_key('timeslice_metric_indicator')
      end

      it 'omits timeslice_metric_indicator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'minimal')
        expect(config).not_to have_key('timeslice_metric_indicator')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_slo', 'typed')
        expect(config['budgeting_method']).to be_a(String)
        expect(config['description']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_slo('first', required_attrs)
        synth.elasticstack_kibana_slo('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_slo')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_slo,
    method: :elasticstack_kibana_slo,
    required_attrs: { budgeting_method: 'test-value', description: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :group_by, :slo_id, :space_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
