# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_fleet_agent_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackFleetAgentPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', namespace: 'test-value' } }

  describe ':elasticstack_fleet_agent_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'test')
        validate_required_attributes(config, [:name, :namespace])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_agent_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_fleet_agent_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_agent_policy('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_fleet_agent_policy.test.id}")
        expect(ref.advanced_monitoring_options).to eq("${elasticstack_fleet_agent_policy.test.advanced_monitoring_options}")
        expect(ref.advanced_settings).to eq("${elasticstack_fleet_agent_policy.test.advanced_settings}")
        expect(ref.global_data_tags).to eq("${elasticstack_fleet_agent_policy.test.global_data_tags}")
        expect(ref.host_name_format).to eq("${elasticstack_fleet_agent_policy.test.host_name_format}")
        expect(ref.inactivity_timeout).to eq("${elasticstack_fleet_agent_policy.test.inactivity_timeout}")
        expect(ref.monitor_logs).to eq("${elasticstack_fleet_agent_policy.test.monitor_logs}")
        expect(ref.monitor_metrics).to eq("${elasticstack_fleet_agent_policy.test.monitor_metrics}")
        expect(ref.policy_id).to eq("${elasticstack_fleet_agent_policy.test.policy_id}")
        expect(ref.required_versions).to eq("${elasticstack_fleet_agent_policy.test.required_versions}")
        expect(ref.space_ids).to eq("${elasticstack_fleet_agent_policy.test.space_ids}")
        expect(ref.unenrollment_timeout).to eq("${elasticstack_fleet_agent_policy.test.unenrollment_timeout}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'test')
        expect(config).not_to have_key('advanced_monitoring_options')
        expect(config).not_to have_key('advanced_settings')
        expect(config).not_to have_key('global_data_tags')
        expect(config).not_to have_key('host_name_format')
        expect(config).not_to have_key('inactivity_timeout')
        expect(config).not_to have_key('monitor_logs')
        expect(config).not_to have_key('monitor_metrics')
        expect(config).not_to have_key('policy_id')
        expect(config).not_to have_key('required_versions')
        expect(config).not_to have_key('space_ids')
        expect(config).not_to have_key('unenrollment_timeout')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_output_id: 'test-value', description: 'test-value', download_source_id: 'test-value', fleet_server_host_id: 'test-value', monitoring_output_id: 'test-value', skip_destroy: true, supports_agentless: true, sys_monitoring: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'full')
        expect(config).to have_key('data_output_id')
        expect(config).to have_key('description')
        expect(config).to have_key('download_source_id')
        expect(config).to have_key('fleet_server_host_id')
        expect(config).to have_key('monitoring_output_id')
        expect(config).to have_key('skip_destroy')
        expect(config).to have_key('supports_agentless')
        expect(config).to have_key('sys_monitoring')
      end
    end

    context 'optional attributes' do
      it 'includes data_output_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(data_output_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('data_output_id')
      end

      it 'omits data_output_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('data_output_id')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes download_source_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(download_source_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('download_source_id')
      end

      it 'omits download_source_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('download_source_id')
      end
      it 'includes fleet_server_host_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(fleet_server_host_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('fleet_server_host_id')
      end

      it 'omits fleet_server_host_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('fleet_server_host_id')
      end
      it 'includes monitoring_output_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(monitoring_output_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('monitoring_output_id')
      end

      it 'omits monitoring_output_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('monitoring_output_id')
      end
      it 'includes skip_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(skip_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('skip_destroy')
      end

      it 'omits skip_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('skip_destroy')
      end
      it 'includes supports_agentless when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(supports_agentless: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('supports_agentless')
      end

      it 'omits supports_agentless when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('supports_agentless')
      end
      it 'includes sys_monitoring when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('opt', required_attrs.merge(sys_monitoring: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'opt')
        expect(config).to have_key('sys_monitoring')
      end

      it 'omits sys_monitoring when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'minimal')
        expect(config).not_to have_key('sys_monitoring')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts skip_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_destroy: val)
          synth.elasticstack_fleet_agent_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', "bool_#{val}")
          expect(config['skip_destroy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts supports_agentless=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(supports_agentless: val)
          synth.elasticstack_fleet_agent_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', "bool_#{val}")
          expect(config['supports_agentless']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts sys_monitoring=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(sys_monitoring: val)
          synth.elasticstack_fleet_agent_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', "bool_#{val}")
          expect(config['sys_monitoring']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_agent_policy', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['namespace']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_agent_policy('first', required_attrs)
        synth.elasticstack_fleet_agent_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_fleet_agent_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_fleet_agent_policy,
    method: :elasticstack_fleet_agent_policy,
    required_attrs: { name: 'test-value', namespace: 'test-value' },
    expected_outputs: [:id, :advanced_monitoring_options, :advanced_settings, :global_data_tags, :host_name_format, :inactivity_timeout, :monitor_logs, :monitor_metrics, :policy_id, :required_versions, :space_ids, :unenrollment_timeout],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:skip_destroy, :supports_agentless, :sys_monitoring]
end
