# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_apm_agent_configuration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackApmAgentConfiguration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { service_name: 'test-value', settings: { 'key1' => 'val1' } } }

  describe ':elasticstack_apm_agent_configuration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'test')
        validate_required_attributes(config, [:service_name, :settings])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_apm_agent_configuration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_apm_agent_configuration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_apm_agent_configuration('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_apm_agent_configuration.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ agent_name: 'test-value', service_environment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'full')
        expect(config).to have_key('agent_name')
        expect(config).to have_key('service_environment')
      end
    end

    context 'optional attributes' do
      it 'includes agent_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('opt', required_attrs.merge(agent_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'opt')
        expect(config).to have_key('agent_name')
      end

      it 'omits agent_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'minimal')
        expect(config).not_to have_key('agent_name')
      end
      it 'includes service_environment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('opt', required_attrs.merge(service_environment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'opt')
        expect(config).to have_key('service_environment')
      end

      it 'omits service_environment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'minimal')
        expect(config).not_to have_key('service_environment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_apm_agent_configuration', 'typed')
        expect(config['service_name']).to be_a(String)
        expect(config['settings']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_apm_agent_configuration('first', required_attrs)
        synth.elasticstack_apm_agent_configuration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_apm_agent_configuration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_apm_agent_configuration,
    method: :elasticstack_apm_agent_configuration,
    required_attrs: { service_name: 'test-value', settings: { 'key1' => 'val1' } },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
