# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_security_detection_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaSecurityDetectionRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', name: 'test-value', type: 'test-value' } }

  describe ':elasticstack_kibana_security_detection_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'test')
        validate_required_attributes(config, [:description, :name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_detection_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_security_detection_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_detection_rule('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_security_detection_rule.test.id}")
        expect(ref.author).to eq("${elasticstack_kibana_security_detection_rule.test.author}")
        expect(ref.created_at).to eq("${elasticstack_kibana_security_detection_rule.test.created_at}")
        expect(ref.created_by).to eq("${elasticstack_kibana_security_detection_rule.test.created_by}")
        expect(ref.enabled).to eq("${elasticstack_kibana_security_detection_rule.test.enabled}")
        expect(ref.false_positives).to eq("${elasticstack_kibana_security_detection_rule.test.false_positives}")
        expect(ref.from).to eq("${elasticstack_kibana_security_detection_rule.test.from}")
        expect(ref.index).to eq("${elasticstack_kibana_security_detection_rule.test.index}")
        expect(ref.interval).to eq("${elasticstack_kibana_security_detection_rule.test.interval}")
        expect(ref.language).to eq("${elasticstack_kibana_security_detection_rule.test.language}")
        expect(ref.max_signals).to eq("${elasticstack_kibana_security_detection_rule.test.max_signals}")
        expect(ref.query).to eq("${elasticstack_kibana_security_detection_rule.test.query}")
        expect(ref.references).to eq("${elasticstack_kibana_security_detection_rule.test.references}")
        expect(ref.revision).to eq("${elasticstack_kibana_security_detection_rule.test.revision}")
        expect(ref.risk_score).to eq("${elasticstack_kibana_security_detection_rule.test.risk_score}")
        expect(ref.rule_id).to eq("${elasticstack_kibana_security_detection_rule.test.rule_id}")
        expect(ref.severity).to eq("${elasticstack_kibana_security_detection_rule.test.severity}")
        expect(ref.space_id).to eq("${elasticstack_kibana_security_detection_rule.test.space_id}")
        expect(ref.tags).to eq("${elasticstack_kibana_security_detection_rule.test.tags}")
        expect(ref.threat_indicator_path).to eq("${elasticstack_kibana_security_detection_rule.test.threat_indicator_path}")
        expect(ref.threat_query).to eq("${elasticstack_kibana_security_detection_rule.test.threat_query}")
        expect(ref.to).to eq("${elasticstack_kibana_security_detection_rule.test.to}")
        expect(ref.updated_at).to eq("${elasticstack_kibana_security_detection_rule.test.updated_at}")
        expect(ref.updated_by).to eq("${elasticstack_kibana_security_detection_rule.test.updated_by}")
        expect(ref.version).to eq("${elasticstack_kibana_security_detection_rule.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'test')
        expect(config).not_to have_key('author')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('created_by')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('false_positives')
        expect(config).not_to have_key('from')
        expect(config).not_to have_key('index')
        expect(config).not_to have_key('interval')
        expect(config).not_to have_key('language')
        expect(config).not_to have_key('max_signals')
        expect(config).not_to have_key('query')
        expect(config).not_to have_key('references')
        expect(config).not_to have_key('revision')
        expect(config).not_to have_key('risk_score')
        expect(config).not_to have_key('rule_id')
        expect(config).not_to have_key('severity')
        expect(config).not_to have_key('space_id')
        expect(config).not_to have_key('tags')
        expect(config).not_to have_key('threat_indicator_path')
        expect(config).not_to have_key('threat_query')
        expect(config).not_to have_key('to')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('updated_by')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ actions: [{ 'key1' => 'val1' }], alert_suppression: { 'key1' => 'val1' }, anomaly_threshold: 3.14, building_block_type: 'test-value', concurrent_searches: 3.14, data_view_id: 'test-value', exceptions_list: [{ 'key1' => 'val1' }], filters: 'test-value', history_window_start: 'test-value', investigation_fields: ['test-value'], items_per_search: 3.14, license: 'test-value', machine_learning_job_id: ['test-value'], namespace: 'test-value', new_terms_fields: ['test-value'], note: 'test-value', related_integrations: [{ 'key1' => 'val1' }], required_fields: [{ 'key1' => 'val1' }], response_actions: [{ 'key1' => 'val1' }], risk_score_mapping: [{ 'key1' => 'val1' }], rule_name_override: 'test-value', saved_id: 'test-value', setup: 'test-value', severity_mapping: [{ 'key1' => 'val1' }], threat: [{ 'key1' => 'val1' }], threat_filters: ['test-value'], threat_index: ['test-value'], threat_mapping: [{ 'key1' => 'val1' }], threshold: { 'key1' => 'val1' }, tiebreaker_field: 'test-value', timeline_id: 'test-value', timeline_title: 'test-value', timestamp_override: 'test-value', timestamp_override_fallback_disabled: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'full')
        expect(config).to have_key('actions')
        expect(config).to have_key('alert_suppression')
        expect(config).to have_key('anomaly_threshold')
        expect(config).to have_key('building_block_type')
        expect(config).to have_key('concurrent_searches')
        expect(config).to have_key('data_view_id')
        expect(config).to have_key('exceptions_list')
        expect(config).to have_key('filters')
        expect(config).to have_key('history_window_start')
        expect(config).to have_key('investigation_fields')
        expect(config).to have_key('items_per_search')
        expect(config).to have_key('license')
        expect(config).to have_key('machine_learning_job_id')
        expect(config).to have_key('namespace')
        expect(config).to have_key('new_terms_fields')
        expect(config).to have_key('note')
        expect(config).to have_key('related_integrations')
        expect(config).to have_key('required_fields')
        expect(config).to have_key('response_actions')
        expect(config).to have_key('risk_score_mapping')
        expect(config).to have_key('rule_name_override')
        expect(config).to have_key('saved_id')
        expect(config).to have_key('setup')
        expect(config).to have_key('severity_mapping')
        expect(config).to have_key('threat')
        expect(config).to have_key('threat_filters')
        expect(config).to have_key('threat_index')
        expect(config).to have_key('threat_mapping')
        expect(config).to have_key('threshold')
        expect(config).to have_key('tiebreaker_field')
        expect(config).to have_key('timeline_id')
        expect(config).to have_key('timeline_title')
        expect(config).to have_key('timestamp_override')
        expect(config).to have_key('timestamp_override_fallback_disabled')
      end
    end

    context 'optional attributes' do
      it 'includes actions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(actions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('actions')
      end

      it 'omits actions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('actions')
      end
      it 'includes alert_suppression when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(alert_suppression: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('alert_suppression')
      end

      it 'omits alert_suppression when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('alert_suppression')
      end
      it 'includes anomaly_threshold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(anomaly_threshold: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('anomaly_threshold')
      end

      it 'omits anomaly_threshold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('anomaly_threshold')
      end
      it 'includes building_block_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(building_block_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('building_block_type')
      end

      it 'omits building_block_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('building_block_type')
      end
      it 'includes concurrent_searches when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(concurrent_searches: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('concurrent_searches')
      end

      it 'omits concurrent_searches when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('concurrent_searches')
      end
      it 'includes data_view_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(data_view_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('data_view_id')
      end

      it 'omits data_view_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('data_view_id')
      end
      it 'includes exceptions_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(exceptions_list: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('exceptions_list')
      end

      it 'omits exceptions_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('exceptions_list')
      end
      it 'includes filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(filters: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('filters')
      end

      it 'omits filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('filters')
      end
      it 'includes history_window_start when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(history_window_start: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('history_window_start')
      end

      it 'omits history_window_start when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('history_window_start')
      end
      it 'includes investigation_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(investigation_fields: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('investigation_fields')
      end

      it 'omits investigation_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('investigation_fields')
      end
      it 'includes items_per_search when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(items_per_search: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('items_per_search')
      end

      it 'omits items_per_search when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('items_per_search')
      end
      it 'includes license when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(license: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('license')
      end

      it 'omits license when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('license')
      end
      it 'includes machine_learning_job_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(machine_learning_job_id: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('machine_learning_job_id')
      end

      it 'omits machine_learning_job_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('machine_learning_job_id')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes new_terms_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(new_terms_fields: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('new_terms_fields')
      end

      it 'omits new_terms_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('new_terms_fields')
      end
      it 'includes note when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(note: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('note')
      end

      it 'omits note when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('note')
      end
      it 'includes related_integrations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(related_integrations: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('related_integrations')
      end

      it 'omits related_integrations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('related_integrations')
      end
      it 'includes required_fields when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(required_fields: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('required_fields')
      end

      it 'omits required_fields when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('required_fields')
      end
      it 'includes response_actions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(response_actions: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('response_actions')
      end

      it 'omits response_actions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('response_actions')
      end
      it 'includes risk_score_mapping when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(risk_score_mapping: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('risk_score_mapping')
      end

      it 'omits risk_score_mapping when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('risk_score_mapping')
      end
      it 'includes rule_name_override when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(rule_name_override: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('rule_name_override')
      end

      it 'omits rule_name_override when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('rule_name_override')
      end
      it 'includes saved_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(saved_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('saved_id')
      end

      it 'omits saved_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('saved_id')
      end
      it 'includes setup when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(setup: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('setup')
      end

      it 'omits setup when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('setup')
      end
      it 'includes severity_mapping when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(severity_mapping: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('severity_mapping')
      end

      it 'omits severity_mapping when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('severity_mapping')
      end
      it 'includes threat when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(threat: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('threat')
      end

      it 'omits threat when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('threat')
      end
      it 'includes threat_filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(threat_filters: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('threat_filters')
      end

      it 'omits threat_filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('threat_filters')
      end
      it 'includes threat_index when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(threat_index: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('threat_index')
      end

      it 'omits threat_index when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('threat_index')
      end
      it 'includes threat_mapping when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(threat_mapping: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('threat_mapping')
      end

      it 'omits threat_mapping when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('threat_mapping')
      end
      it 'includes threshold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(threshold: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('threshold')
      end

      it 'omits threshold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('threshold')
      end
      it 'includes tiebreaker_field when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(tiebreaker_field: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('tiebreaker_field')
      end

      it 'omits tiebreaker_field when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('tiebreaker_field')
      end
      it 'includes timeline_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(timeline_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('timeline_id')
      end

      it 'omits timeline_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('timeline_id')
      end
      it 'includes timeline_title when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(timeline_title: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('timeline_title')
      end

      it 'omits timeline_title when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('timeline_title')
      end
      it 'includes timestamp_override when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(timestamp_override: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('timestamp_override')
      end

      it 'omits timestamp_override when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('timestamp_override')
      end
      it 'includes timestamp_override_fallback_disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('opt', required_attrs.merge(timestamp_override_fallback_disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'opt')
        expect(config).to have_key('timestamp_override_fallback_disabled')
      end

      it 'omits timestamp_override_fallback_disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'minimal')
        expect(config).not_to have_key('timestamp_override_fallback_disabled')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts timestamp_override_fallback_disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(timestamp_override_fallback_disabled: val)
          synth.elasticstack_kibana_security_detection_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', "bool_#{val}")
          expect(config['timestamp_override_fallback_disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_detection_rule', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_detection_rule('first', required_attrs)
        synth.elasticstack_kibana_security_detection_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_security_detection_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_security_detection_rule,
    method: :elasticstack_kibana_security_detection_rule,
    required_attrs: { description: 'test-value', name: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :author, :created_at, :created_by, :enabled, :false_positives, :from, :index, :interval, :language, :max_signals, :query, :references, :revision, :risk_score, :rule_id, :severity, :space_id, :tags, :threat_indicator_path, :threat_query, :to, :updated_at, :updated_by, :version],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:timestamp_override_fallback_disabled]
end
