# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_fleet_server_host resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackFleetServerHost do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { hosts: ['test-value'], name: 'test-value' } }

  describe ':elasticstack_fleet_server_host' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_fleet_server_host', 'test')
        validate_required_attributes(config, [:hosts, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_server_host('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_fleet_server_host)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_server_host('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_fleet_server_host.test.id}")
        expect(ref.host_id).to eq("${elasticstack_fleet_server_host.test.host_id}")
        expect(ref.space_ids).to eq("${elasticstack_fleet_server_host.test.space_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_server_host', 'test')
        expect(config).not_to have_key('host_id')
        expect(config).not_to have_key('space_ids')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ default: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_server_host', 'full')
        expect(config).to have_key('default')
      end
    end

    context 'optional attributes' do
      it 'includes default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('opt', required_attrs.merge(default: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_server_host', 'opt')
        expect(config).to have_key('default')
      end

      it 'omits default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_server_host', 'minimal')
        expect(config).not_to have_key('default')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(default: val)
          synth.elasticstack_fleet_server_host("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_server_host', "bool_#{val}")
          expect(config['default']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_server_host', 'typed')
        expect(config['hosts']).to be_a(Array)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_server_host('first', required_attrs)
        synth.elasticstack_fleet_server_host('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_fleet_server_host')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_fleet_server_host,
    method: :elasticstack_fleet_server_host,
    required_attrs: { hosts: ['test-value'], name: 'test-value' },
    expected_outputs: [:id, :host_id, :space_ids],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:default]
end
