# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_import_saved_objects resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaImportSavedObjects do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { file_contents: 'test-value' } }

  describe ':elasticstack_kibana_import_saved_objects' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'test')
        validate_required_attributes(config, [:file_contents])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_import_saved_objects('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_import_saved_objects)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_import_saved_objects('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_import_saved_objects.test.id}")
        expect(ref.errors).to eq("${elasticstack_kibana_import_saved_objects.test.errors}")
        expect(ref.success).to eq("${elasticstack_kibana_import_saved_objects.test.success}")
        expect(ref.success_count).to eq("${elasticstack_kibana_import_saved_objects.test.success_count}")
        expect(ref.success_results).to eq("${elasticstack_kibana_import_saved_objects.test.success_results}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'test')
        expect(config).not_to have_key('errors')
        expect(config).not_to have_key('success')
        expect(config).not_to have_key('success_count')
        expect(config).not_to have_key('success_results')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ignore_import_errors: true, overwrite: true, space_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'full')
        expect(config).to have_key('ignore_import_errors')
        expect(config).to have_key('overwrite')
        expect(config).to have_key('space_id')
      end
    end

    context 'optional attributes' do
      it 'includes ignore_import_errors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('opt', required_attrs.merge(ignore_import_errors: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'opt')
        expect(config).to have_key('ignore_import_errors')
      end

      it 'omits ignore_import_errors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'minimal')
        expect(config).not_to have_key('ignore_import_errors')
      end
      it 'includes overwrite when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('opt', required_attrs.merge(overwrite: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'opt')
        expect(config).to have_key('overwrite')
      end

      it 'omits overwrite when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'minimal')
        expect(config).not_to have_key('overwrite')
      end
      it 'includes space_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('opt', required_attrs.merge(space_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'opt')
        expect(config).to have_key('space_id')
      end

      it 'omits space_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'minimal')
        expect(config).not_to have_key('space_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts ignore_import_errors=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_import_errors: val)
          synth.elasticstack_kibana_import_saved_objects("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', "bool_#{val}")
          expect(config['ignore_import_errors']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts overwrite=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(overwrite: val)
          synth.elasticstack_kibana_import_saved_objects("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', "bool_#{val}")
          expect(config['overwrite']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_import_saved_objects', 'typed')
        expect(config['file_contents']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_import_saved_objects('first', required_attrs)
        synth.elasticstack_kibana_import_saved_objects('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_import_saved_objects')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_import_saved_objects,
    method: :elasticstack_kibana_import_saved_objects,
    required_attrs: { file_contents: 'test-value' },
    expected_outputs: [:id, :errors, :success, :success_count, :success_results],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:ignore_import_errors, :overwrite]
end
