# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_install_prebuilt_rules resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaInstallPrebuiltRules do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':elasticstack_kibana_install_prebuilt_rules' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_install_prebuilt_rules('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_install_prebuilt_rules', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_install_prebuilt_rules('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_install_prebuilt_rules)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_install_prebuilt_rules('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_install_prebuilt_rules.test.id}")
        expect(ref.rules_installed).to eq("${elasticstack_kibana_install_prebuilt_rules.test.rules_installed}")
        expect(ref.rules_not_installed).to eq("${elasticstack_kibana_install_prebuilt_rules.test.rules_not_installed}")
        expect(ref.rules_not_updated).to eq("${elasticstack_kibana_install_prebuilt_rules.test.rules_not_updated}")
        expect(ref.space_id).to eq("${elasticstack_kibana_install_prebuilt_rules.test.space_id}")
        expect(ref.timelines_installed).to eq("${elasticstack_kibana_install_prebuilt_rules.test.timelines_installed}")
        expect(ref.timelines_not_installed).to eq("${elasticstack_kibana_install_prebuilt_rules.test.timelines_not_installed}")
        expect(ref.timelines_not_updated).to eq("${elasticstack_kibana_install_prebuilt_rules.test.timelines_not_updated}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_install_prebuilt_rules('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_install_prebuilt_rules', 'test')
        expect(config).not_to have_key('rules_installed')
        expect(config).not_to have_key('rules_not_installed')
        expect(config).not_to have_key('rules_not_updated')
        expect(config).not_to have_key('space_id')
        expect(config).not_to have_key('timelines_installed')
        expect(config).not_to have_key('timelines_not_installed')
        expect(config).not_to have_key('timelines_not_updated')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_install_prebuilt_rules('first', required_attrs)
        synth.elasticstack_kibana_install_prebuilt_rules('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_install_prebuilt_rules')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_install_prebuilt_rules,
    method: :elasticstack_kibana_install_prebuilt_rules,
    required_attrs: {},
    expected_outputs: [:id, :rules_installed, :rules_not_installed, :rules_not_updated, :space_id, :timelines_installed, :timelines_not_installed, :timelines_not_updated],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
