# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_data_stream resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchDataStream do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':elasticstack_elasticsearch_data_stream' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_data_stream('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_data_stream)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_data_stream('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_data_stream.test.id}")
        expect(ref.generation).to eq("${elasticstack_elasticsearch_data_stream.test.generation}")
        expect(ref.hidden).to eq("${elasticstack_elasticsearch_data_stream.test.hidden}")
        expect(ref.ilm_policy).to eq("${elasticstack_elasticsearch_data_stream.test.ilm_policy}")
        expect(ref.indices).to eq("${elasticstack_elasticsearch_data_stream.test.indices}")
        expect(ref.metadata).to eq("${elasticstack_elasticsearch_data_stream.test.metadata}")
        expect(ref.replicated).to eq("${elasticstack_elasticsearch_data_stream.test.replicated}")
        expect(ref.status).to eq("${elasticstack_elasticsearch_data_stream.test.status}")
        expect(ref.system).to eq("${elasticstack_elasticsearch_data_stream.test.system}")
        expect(ref.template).to eq("${elasticstack_elasticsearch_data_stream.test.template}")
        expect(ref.timestamp_field).to eq("${elasticstack_elasticsearch_data_stream.test.timestamp_field}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream', 'test')
        expect(config).not_to have_key('generation')
        expect(config).not_to have_key('hidden')
        expect(config).not_to have_key('ilm_policy')
        expect(config).not_to have_key('indices')
        expect(config).not_to have_key('metadata')
        expect(config).not_to have_key('replicated')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('system')
        expect(config).not_to have_key('template')
        expect(config).not_to have_key('timestamp_field')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ elasticsearch_connection: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream', 'full')
        expect(config).to have_key('elasticsearch_connection')
      end
    end

    context 'optional attributes' do
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream('first', required_attrs)
        synth.elasticstack_elasticsearch_data_stream('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_data_stream')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_data_stream,
    method: :elasticstack_elasticsearch_data_stream,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :generation, :hidden, :ilm_policy, :indices, :metadata, :replicated, :status, :system, :template, :timestamp_field],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
