# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_security_api_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchSecurityApiKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':elasticstack_elasticsearch_security_api_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_api_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_security_api_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_api_key('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_security_api_key.test.id}")
        expect(ref.api_key).to eq("${elasticstack_elasticsearch_security_api_key.test.api_key}")
        expect(ref.encoded).to eq("${elasticstack_elasticsearch_security_api_key.test.encoded}")
        expect(ref.expiration_timestamp).to eq("${elasticstack_elasticsearch_security_api_key.test.expiration_timestamp}")
        expect(ref.key_id).to eq("${elasticstack_elasticsearch_security_api_key.test.key_id}")
        expect(ref.metadata).to eq("${elasticstack_elasticsearch_security_api_key.test.metadata}")
        expect(ref.role_descriptors).to eq("${elasticstack_elasticsearch_security_api_key.test.role_descriptors}")
        expect(ref.type).to eq("${elasticstack_elasticsearch_security_api_key.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'test')
        expect(config).not_to have_key('api_key')
        expect(config).not_to have_key('encoded')
        expect(config).not_to have_key('expiration_timestamp')
        expect(config).not_to have_key('key_id')
        expect(config).not_to have_key('metadata')
        expect(config).not_to have_key('role_descriptors')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access: { 'key1' => 'val1' }, elasticsearch_connection: [{ 'key1' => 'val1' }], expiration: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'full')
        expect(config).to have_key('access')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('expiration')
      end
    end

    context 'optional attributes' do
      it 'includes access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('opt', required_attrs.merge(access: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'opt')
        expect(config).to have_key('access')
      end

      it 'omits access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'minimal')
        expect(config).not_to have_key('access')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes expiration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('opt', required_attrs.merge(expiration: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'opt')
        expect(config).to have_key('expiration')
      end

      it 'omits expiration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'minimal')
        expect(config).not_to have_key('expiration')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:api_key, :encoded]
        expect(sensitive_fields).to include(:api_key)
        expect(sensitive_fields).to include(:encoded)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_api_key', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_api_key('first', required_attrs)
        synth.elasticstack_elasticsearch_security_api_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_security_api_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_security_api_key,
    method: :elasticstack_elasticsearch_security_api_key,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :api_key, :encoded, :expiration_timestamp, :key_id, :metadata, :role_descriptors, :type],
    sensitive_fields: [:api_key, :encoded],
    immutable_fields: [],
    boolean_fields: []
end
