# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_fleet_output resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackFleetOutput do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { hosts: ['test-value'], name: 'test-value', type: 'test-value' } }

  describe ':elasticstack_fleet_output' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'test')
        validate_required_attributes(config, [:hosts, :name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_output('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_fleet_output)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_output('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_fleet_output.test.id}")
        expect(ref.default_integrations).to eq("${elasticstack_fleet_output.test.default_integrations}")
        expect(ref.default_monitoring).to eq("${elasticstack_fleet_output.test.default_monitoring}")
        expect(ref.output_id).to eq("${elasticstack_fleet_output.test.output_id}")
        expect(ref.space_ids).to eq("${elasticstack_fleet_output.test.space_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'test')
        expect(config).not_to have_key('default_integrations')
        expect(config).not_to have_key('default_monitoring')
        expect(config).not_to have_key('output_id')
        expect(config).not_to have_key('space_ids')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ca_sha256: 'test-value', ca_trusted_fingerprint: 'test-value', config_yaml: 'test-value', kafka: { 'key1' => 'val1' }, ssl: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'full')
        expect(config).to have_key('ca_sha256')
        expect(config).to have_key('ca_trusted_fingerprint')
        expect(config).to have_key('config_yaml')
        expect(config).to have_key('kafka')
        expect(config).to have_key('ssl')
      end
    end

    context 'optional attributes' do
      it 'includes ca_sha256 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('opt', required_attrs.merge(ca_sha256: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'opt')
        expect(config).to have_key('ca_sha256')
      end

      it 'omits ca_sha256 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'minimal')
        expect(config).not_to have_key('ca_sha256')
      end
      it 'includes ca_trusted_fingerprint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('opt', required_attrs.merge(ca_trusted_fingerprint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'opt')
        expect(config).to have_key('ca_trusted_fingerprint')
      end

      it 'omits ca_trusted_fingerprint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'minimal')
        expect(config).not_to have_key('ca_trusted_fingerprint')
      end
      it 'includes config_yaml when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('opt', required_attrs.merge(config_yaml: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'opt')
        expect(config).to have_key('config_yaml')
      end

      it 'omits config_yaml when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'minimal')
        expect(config).not_to have_key('config_yaml')
      end
      it 'includes kafka when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('opt', required_attrs.merge(kafka: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'opt')
        expect(config).to have_key('kafka')
      end

      it 'omits kafka when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'minimal')
        expect(config).not_to have_key('kafka')
      end
      it 'includes ssl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('opt', required_attrs.merge(ssl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'opt')
        expect(config).to have_key('ssl')
      end

      it 'omits ssl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'minimal')
        expect(config).not_to have_key('ssl')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:config_yaml]
        expect(sensitive_fields).to include(:config_yaml)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_output', 'typed')
        expect(config['hosts']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_output('first', required_attrs)
        synth.elasticstack_fleet_output('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_fleet_output')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_fleet_output,
    method: :elasticstack_fleet_output,
    required_attrs: { hosts: ['test-value'], name: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :default_integrations, :default_monitoring, :output_id, :space_ids],
    sensitive_fields: [:config_yaml],
    immutable_fields: [],
    boolean_fields: []
end
