# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_data_stream_lifecycle resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchDataStreamLifecycle do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':elasticstack_elasticsearch_data_stream_lifecycle' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_data_stream_lifecycle('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_data_stream_lifecycle)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_data_stream_lifecycle('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_data_stream_lifecycle.test.id}")
        expect(ref.enabled).to eq("${elasticstack_elasticsearch_data_stream_lifecycle.test.enabled}")
        expect(ref.expand_wildcards).to eq("${elasticstack_elasticsearch_data_stream_lifecycle.test.expand_wildcards}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'test')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('expand_wildcards')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ data_retention: 'test-value', downsampling: [{ 'key1' => 'val1' }], elasticsearch_connection: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'full')
        expect(config).to have_key('data_retention')
        expect(config).to have_key('downsampling')
        expect(config).to have_key('elasticsearch_connection')
      end
    end

    context 'optional attributes' do
      it 'includes data_retention when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('opt', required_attrs.merge(data_retention: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'opt')
        expect(config).to have_key('data_retention')
      end

      it 'omits data_retention when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'minimal')
        expect(config).not_to have_key('data_retention')
      end
      it 'includes downsampling when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('opt', required_attrs.merge(downsampling: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'opt')
        expect(config).to have_key('downsampling')
      end

      it 'omits downsampling when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'minimal')
        expect(config).not_to have_key('downsampling')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_data_stream_lifecycle', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('first', required_attrs)
        synth.elasticstack_elasticsearch_data_stream_lifecycle('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_data_stream_lifecycle')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_data_stream_lifecycle,
    method: :elasticstack_elasticsearch_data_stream_lifecycle,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :enabled, :expand_wildcards],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
