# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_snapshot_lifecycle resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchSnapshotLifecycle do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', repository: 'test-value', schedule: 'test-value' } }

  describe ':elasticstack_elasticsearch_snapshot_lifecycle' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'test')
        validate_required_attributes(config, [:name, :repository, :schedule])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_snapshot_lifecycle('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_snapshot_lifecycle)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_snapshot_lifecycle('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_snapshot_lifecycle.test.id}")
        expect(ref.feature_states).to eq("${elasticstack_elasticsearch_snapshot_lifecycle.test.feature_states}")
        expect(ref.indices).to eq("${elasticstack_elasticsearch_snapshot_lifecycle.test.indices}")
        expect(ref.metadata).to eq("${elasticstack_elasticsearch_snapshot_lifecycle.test.metadata}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'test')
        expect(config).not_to have_key('feature_states')
        expect(config).not_to have_key('indices')
        expect(config).not_to have_key('metadata')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ elasticsearch_connection: [{ 'key1' => 'val1' }], expand_wildcards: 'test-value', expire_after: 'test-value', ignore_unavailable: true, include_global_state: true, max_count: 3.14, min_count: 3.14, partial: true, snapshot_name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'full')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('expand_wildcards')
        expect(config).to have_key('expire_after')
        expect(config).to have_key('ignore_unavailable')
        expect(config).to have_key('include_global_state')
        expect(config).to have_key('max_count')
        expect(config).to have_key('min_count')
        expect(config).to have_key('partial')
        expect(config).to have_key('snapshot_name')
      end
    end

    context 'optional attributes' do
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes expand_wildcards when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(expand_wildcards: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('expand_wildcards')
      end

      it 'omits expand_wildcards when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('expand_wildcards')
      end
      it 'includes expire_after when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(expire_after: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('expire_after')
      end

      it 'omits expire_after when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('expire_after')
      end
      it 'includes ignore_unavailable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(ignore_unavailable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('ignore_unavailable')
      end

      it 'omits ignore_unavailable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('ignore_unavailable')
      end
      it 'includes include_global_state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(include_global_state: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('include_global_state')
      end

      it 'omits include_global_state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('include_global_state')
      end
      it 'includes max_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(max_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('max_count')
      end

      it 'omits max_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('max_count')
      end
      it 'includes min_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(min_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('min_count')
      end

      it 'omits min_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('min_count')
      end
      it 'includes partial when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(partial: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('partial')
      end

      it 'omits partial when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('partial')
      end
      it 'includes snapshot_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('opt', required_attrs.merge(snapshot_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'opt')
        expect(config).to have_key('snapshot_name')
      end

      it 'omits snapshot_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'minimal')
        expect(config).not_to have_key('snapshot_name')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts ignore_unavailable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_unavailable: val)
          synth.elasticstack_elasticsearch_snapshot_lifecycle("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', "bool_#{val}")
          expect(config['ignore_unavailable']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts include_global_state=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(include_global_state: val)
          synth.elasticstack_elasticsearch_snapshot_lifecycle("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', "bool_#{val}")
          expect(config['include_global_state']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts partial=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(partial: val)
          synth.elasticstack_elasticsearch_snapshot_lifecycle("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', "bool_#{val}")
          expect(config['partial']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_snapshot_lifecycle', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['repository']).to be_a(String)
        expect(config['schedule']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('first', required_attrs)
        synth.elasticstack_elasticsearch_snapshot_lifecycle('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_snapshot_lifecycle')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_snapshot_lifecycle,
    method: :elasticstack_elasticsearch_snapshot_lifecycle,
    required_attrs: { name: 'test-value', repository: 'test-value', schedule: 'test-value' },
    expected_outputs: [:id, :feature_states, :indices, :metadata],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:ignore_unavailable, :include_global_state, :partial]
end
