# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_security_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchSecurityUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { roles: ['test-value'], username: 'test-value' } }

  describe ':elasticstack_elasticsearch_security_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'test')
        validate_required_attributes(config, [:roles, :username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_security_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_user('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_security_user.test.id}")
        expect(ref.email).to eq("${elasticstack_elasticsearch_security_user.test.email}")
        expect(ref.enabled).to eq("${elasticstack_elasticsearch_security_user.test.enabled}")
        expect(ref.full_name).to eq("${elasticstack_elasticsearch_security_user.test.full_name}")
        expect(ref.metadata).to eq("${elasticstack_elasticsearch_security_user.test.metadata}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'test')
        expect(config).not_to have_key('email')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('full_name')
        expect(config).not_to have_key('metadata')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ elasticsearch_connection: [{ 'key1' => 'val1' }], password: 'test-value', password_hash: 'test-value', password_wo: 'test-value', password_wo_version: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'full')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('password')
        expect(config).to have_key('password_hash')
        expect(config).to have_key('password_wo')
        expect(config).to have_key('password_wo_version')
      end
    end

    context 'optional attributes' do
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('opt', required_attrs.merge(password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'opt')
        expect(config).to have_key('password')
      end

      it 'omits password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'minimal')
        expect(config).not_to have_key('password')
      end
      it 'includes password_hash when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('opt', required_attrs.merge(password_hash: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'opt')
        expect(config).to have_key('password_hash')
      end

      it 'omits password_hash when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'minimal')
        expect(config).not_to have_key('password_hash')
      end
      it 'includes password_wo when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('opt', required_attrs.merge(password_wo: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'opt')
        expect(config).to have_key('password_wo')
      end

      it 'omits password_wo when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'minimal')
        expect(config).not_to have_key('password_wo')
      end
      it 'includes password_wo_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('opt', required_attrs.merge(password_wo_version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'opt')
        expect(config).to have_key('password_wo_version')
      end

      it 'omits password_wo_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'minimal')
        expect(config).not_to have_key('password_wo_version')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password, :password_hash, :password_wo]
        expect(sensitive_fields).to include(:password)
        expect(sensitive_fields).to include(:password_hash)
        expect(sensitive_fields).to include(:password_wo)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_user', 'typed')
        expect(config['roles']).to be_a(Array)
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_user('first', required_attrs)
        synth.elasticstack_elasticsearch_security_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_security_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_security_user,
    method: :elasticstack_elasticsearch_security_user,
    required_attrs: { roles: ['test-value'], username: 'test-value' },
    expected_outputs: [:id, :email, :enabled, :full_name, :metadata],
    sensitive_fields: [:password, :password_hash, :password_wo],
    immutable_fields: [],
    boolean_fields: []
end
