# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_ml_datafeed_state resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchMlDatafeedState do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { datafeed_id: 'test-value', state: 'test-value' } }

  describe ':elasticstack_elasticsearch_ml_datafeed_state' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'test')
        validate_required_attributes(config, [:datafeed_id, :state])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_ml_datafeed_state('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_ml_datafeed_state)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_ml_datafeed_state('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_ml_datafeed_state.test.id}")
        expect(ref.datafeed_timeout).to eq("${elasticstack_elasticsearch_ml_datafeed_state.test.datafeed_timeout}")
        expect(ref.force).to eq("${elasticstack_elasticsearch_ml_datafeed_state.test.force}")
        expect(ref.start).to eq("${elasticstack_elasticsearch_ml_datafeed_state.test.start}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'test')
        expect(config).not_to have_key('datafeed_timeout')
        expect(config).not_to have_key('force')
        expect(config).not_to have_key('start')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ elasticsearch_connection: [{ 'key1' => 'val1' }], end: 'test-value', timeouts: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'full')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('end')
        expect(config).to have_key('timeouts')
      end
    end

    context 'optional attributes' do
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes end when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('opt', required_attrs.merge(end: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'opt')
        expect(config).to have_key('end')
      end

      it 'omits end when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'minimal')
        expect(config).not_to have_key('end')
      end
      it 'includes timeouts when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('opt', required_attrs.merge(timeouts: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'opt')
        expect(config).to have_key('timeouts')
      end

      it 'omits timeouts when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'minimal')
        expect(config).not_to have_key('timeouts')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_datafeed_state', 'typed')
        expect(config['datafeed_id']).to be_a(String)
        expect(config['state']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_datafeed_state('first', required_attrs)
        synth.elasticstack_elasticsearch_ml_datafeed_state('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_ml_datafeed_state')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_ml_datafeed_state,
    method: :elasticstack_elasticsearch_ml_datafeed_state,
    required_attrs: { datafeed_id: 'test-value', state: 'test-value' },
    expected_outputs: [:id, :datafeed_timeout, :force, :start],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
