# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_fleet_integration resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackFleetIntegration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', version: 'test-value' } }

  describe ':elasticstack_fleet_integration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'test')
        validate_required_attributes(config, [:name, :version])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_integration('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_fleet_integration)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_integration('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_fleet_integration.test.id}")
        expect(ref.space_id).to eq("${elasticstack_fleet_integration.test.space_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'test')
        expect(config).not_to have_key('space_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ force: true, ignore_constraints: true, ignore_mapping_update_errors: true, prerelease: true, skip_data_stream_rollover: true, skip_destroy: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'full')
        expect(config).to have_key('force')
        expect(config).to have_key('ignore_constraints')
        expect(config).to have_key('ignore_mapping_update_errors')
        expect(config).to have_key('prerelease')
        expect(config).to have_key('skip_data_stream_rollover')
        expect(config).to have_key('skip_destroy')
      end
    end

    context 'optional attributes' do
      it 'includes force when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('opt', required_attrs.merge(force: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'opt')
        expect(config).to have_key('force')
      end

      it 'omits force when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'minimal')
        expect(config).not_to have_key('force')
      end
      it 'includes ignore_constraints when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('opt', required_attrs.merge(ignore_constraints: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'opt')
        expect(config).to have_key('ignore_constraints')
      end

      it 'omits ignore_constraints when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'minimal')
        expect(config).not_to have_key('ignore_constraints')
      end
      it 'includes ignore_mapping_update_errors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('opt', required_attrs.merge(ignore_mapping_update_errors: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'opt')
        expect(config).to have_key('ignore_mapping_update_errors')
      end

      it 'omits ignore_mapping_update_errors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'minimal')
        expect(config).not_to have_key('ignore_mapping_update_errors')
      end
      it 'includes prerelease when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('opt', required_attrs.merge(prerelease: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'opt')
        expect(config).to have_key('prerelease')
      end

      it 'omits prerelease when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'minimal')
        expect(config).not_to have_key('prerelease')
      end
      it 'includes skip_data_stream_rollover when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('opt', required_attrs.merge(skip_data_stream_rollover: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'opt')
        expect(config).to have_key('skip_data_stream_rollover')
      end

      it 'omits skip_data_stream_rollover when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'minimal')
        expect(config).not_to have_key('skip_data_stream_rollover')
      end
      it 'includes skip_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('opt', required_attrs.merge(skip_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'opt')
        expect(config).to have_key('skip_destroy')
      end

      it 'omits skip_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'minimal')
        expect(config).not_to have_key('skip_destroy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force: val)
          synth.elasticstack_fleet_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration', "bool_#{val}")
          expect(config['force']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ignore_constraints=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_constraints: val)
          synth.elasticstack_fleet_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration', "bool_#{val}")
          expect(config['ignore_constraints']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ignore_mapping_update_errors=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ignore_mapping_update_errors: val)
          synth.elasticstack_fleet_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration', "bool_#{val}")
          expect(config['ignore_mapping_update_errors']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts prerelease=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(prerelease: val)
          synth.elasticstack_fleet_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration', "bool_#{val}")
          expect(config['prerelease']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_data_stream_rollover=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_data_stream_rollover: val)
          synth.elasticstack_fleet_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration', "bool_#{val}")
          expect(config['skip_data_stream_rollover']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_destroy: val)
          synth.elasticstack_fleet_integration("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration', "bool_#{val}")
          expect(config['skip_destroy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_integration', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['version']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration('first', required_attrs)
        synth.elasticstack_fleet_integration('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_fleet_integration')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_fleet_integration,
    method: :elasticstack_fleet_integration,
    required_attrs: { name: 'test-value', version: 'test-value' },
    expected_outputs: [:id, :space_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:force, :ignore_constraints, :ignore_mapping_update_errors, :prerelease, :skip_data_stream_rollover, :skip_destroy]
end
