# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_security_enable_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaSecurityEnableRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', value: 'test-value' } }

  describe ':elasticstack_kibana_security_enable_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_enable_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_enable_rule', 'test')
        validate_required_attributes(config, [:key, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_enable_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_security_enable_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_enable_rule('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_security_enable_rule.test.id}")
        expect(ref.all_rules_enabled).to eq("${elasticstack_kibana_security_enable_rule.test.all_rules_enabled}")
        expect(ref.disable_on_destroy).to eq("${elasticstack_kibana_security_enable_rule.test.disable_on_destroy}")
        expect(ref.space_id).to eq("${elasticstack_kibana_security_enable_rule.test.space_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_enable_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_enable_rule', 'test')
        expect(config).not_to have_key('all_rules_enabled')
        expect(config).not_to have_key('disable_on_destroy')
        expect(config).not_to have_key('space_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_enable_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_enable_rule', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_enable_rule('first', required_attrs)
        synth.elasticstack_kibana_security_enable_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_security_enable_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_security_enable_rule,
    method: :elasticstack_kibana_security_enable_rule,
    required_attrs: { key: 'test-value', value: 'test-value' },
    expected_outputs: [:id, :all_rules_enabled, :disable_on_destroy, :space_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
