# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_security_list_item resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaSecurityListItem do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { list_id: 'test-value', value: 'test-value' } }

  describe ':elasticstack_kibana_security_list_item' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_list_item', 'test')
        validate_required_attributes(config, [:list_id, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_list_item('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_security_list_item)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_list_item('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_security_list_item.test.id}")
        expect(ref.created_at).to eq("${elasticstack_kibana_security_list_item.test.created_at}")
        expect(ref.created_by).to eq("${elasticstack_kibana_security_list_item.test.created_by}")
        expect(ref.list_item_id).to eq("${elasticstack_kibana_security_list_item.test.list_item_id}")
        expect(ref.space_id).to eq("${elasticstack_kibana_security_list_item.test.space_id}")
        expect(ref.updated_at).to eq("${elasticstack_kibana_security_list_item.test.updated_at}")
        expect(ref.updated_by).to eq("${elasticstack_kibana_security_list_item.test.updated_by}")
        expect(ref.version_id).to eq("${elasticstack_kibana_security_list_item.test.version_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_list_item', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('created_by')
        expect(config).not_to have_key('list_item_id')
        expect(config).not_to have_key('space_id')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('updated_by')
        expect(config).not_to have_key('version_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ meta: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_list_item', 'full')
        expect(config).to have_key('meta')
      end
    end

    context 'optional attributes' do
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('opt', required_attrs.merge(meta: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_list_item', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_list_item', 'minimal')
        expect(config).not_to have_key('meta')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_list_item', 'typed')
        expect(config['list_id']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_list_item('first', required_attrs)
        synth.elasticstack_kibana_security_list_item('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_security_list_item')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_security_list_item,
    method: :elasticstack_kibana_security_list_item,
    required_attrs: { list_id: 'test-value', value: 'test-value' },
    expected_outputs: [:id, :created_at, :created_by, :list_item_id, :space_id, :updated_at, :updated_by, :version_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
