# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_watch resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchWatch do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { trigger: 'test-value', watch_id: 'test-value' } }

  describe ':elasticstack_elasticsearch_watch' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'test')
        validate_required_attributes(config, [:trigger, :watch_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_watch('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_watch)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_watch('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_watch.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ actions: 'test-value', active: true, condition: 'test-value', input: 'test-value', metadata: 'test-value', throttle_period_in_millis: 3.14, transform: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'full')
        expect(config).to have_key('actions')
        expect(config).to have_key('active')
        expect(config).to have_key('condition')
        expect(config).to have_key('input')
        expect(config).to have_key('metadata')
        expect(config).to have_key('throttle_period_in_millis')
        expect(config).to have_key('transform')
      end
    end

    context 'optional attributes' do
      it 'includes actions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(actions: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('actions')
      end

      it 'omits actions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('actions')
      end
      it 'includes active when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(active: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('active')
      end

      it 'omits active when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('active')
      end
      it 'includes condition when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(condition: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('condition')
      end

      it 'omits condition when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('condition')
      end
      it 'includes input when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(input: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('input')
      end

      it 'omits input when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('input')
      end
      it 'includes metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(metadata: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('metadata')
      end

      it 'omits metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('metadata')
      end
      it 'includes throttle_period_in_millis when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(throttle_period_in_millis: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('throttle_period_in_millis')
      end

      it 'omits throttle_period_in_millis when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('throttle_period_in_millis')
      end
      it 'includes transform when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('opt', required_attrs.merge(transform: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'opt')
        expect(config).to have_key('transform')
      end

      it 'omits transform when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'minimal')
        expect(config).not_to have_key('transform')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts active=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(active: val)
          synth.elasticstack_elasticsearch_watch("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', "bool_#{val}")
          expect(config['active']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_watch', 'typed')
        expect(config['trigger']).to be_a(String)
        expect(config['watch_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_watch('first', required_attrs)
        synth.elasticstack_elasticsearch_watch('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_watch')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_watch,
    method: :elasticstack_elasticsearch_watch,
    required_attrs: { trigger: 'test-value', watch_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:active]
end
