# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_ml_anomaly_detection_job resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchMlAnomalyDetectionJob do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { analysis_config: { 'key1' => 'val1' }, data_description: { 'key1' => 'val1' }, job_id: 'test-value' } }

  describe ':elasticstack_elasticsearch_ml_anomaly_detection_job' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'test')
        validate_required_attributes(config, [:analysis_config, :data_description, :job_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_ml_anomaly_detection_job('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_ml_anomaly_detection_job)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_ml_anomaly_detection_job('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.id}")
        expect(ref.allow_lazy_open).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.allow_lazy_open}")
        expect(ref.analysis_limits).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.analysis_limits}")
        expect(ref.create_time).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.create_time}")
        expect(ref.daily_model_snapshot_retention_after_days).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.daily_model_snapshot_retention_after_days}")
        expect(ref.job_type).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.job_type}")
        expect(ref.job_version).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.job_version}")
        expect(ref.model_snapshot_id).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.model_snapshot_id}")
        expect(ref.model_snapshot_retention_days).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.model_snapshot_retention_days}")
        expect(ref.results_index_name).to eq("${elasticstack_elasticsearch_ml_anomaly_detection_job.test.results_index_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'test')
        expect(config).not_to have_key('allow_lazy_open')
        expect(config).not_to have_key('analysis_limits')
        expect(config).not_to have_key('create_time')
        expect(config).not_to have_key('daily_model_snapshot_retention_after_days')
        expect(config).not_to have_key('job_type')
        expect(config).not_to have_key('job_version')
        expect(config).not_to have_key('model_snapshot_id')
        expect(config).not_to have_key('model_snapshot_retention_days')
        expect(config).not_to have_key('results_index_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ background_persist_interval: 'test-value', custom_settings: 'test-value', description: 'test-value', elasticsearch_connection: [{ 'key1' => 'val1' }], groups: ['test-value'], model_plot_config: { 'key1' => 'val1' }, renormalization_window_days: 3.14, results_retention_days: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'full')
        expect(config).to have_key('background_persist_interval')
        expect(config).to have_key('custom_settings')
        expect(config).to have_key('description')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('groups')
        expect(config).to have_key('model_plot_config')
        expect(config).to have_key('renormalization_window_days')
        expect(config).to have_key('results_retention_days')
      end
    end

    context 'optional attributes' do
      it 'includes background_persist_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(background_persist_interval: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('background_persist_interval')
      end

      it 'omits background_persist_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('background_persist_interval')
      end
      it 'includes custom_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(custom_settings: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('custom_settings')
      end

      it 'omits custom_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('custom_settings')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes groups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(groups: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('groups')
      end

      it 'omits groups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('groups')
      end
      it 'includes model_plot_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(model_plot_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('model_plot_config')
      end

      it 'omits model_plot_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('model_plot_config')
      end
      it 'includes renormalization_window_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(renormalization_window_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('renormalization_window_days')
      end

      it 'omits renormalization_window_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('renormalization_window_days')
      end
      it 'includes results_retention_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('opt', required_attrs.merge(results_retention_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'opt')
        expect(config).to have_key('results_retention_days')
      end

      it 'omits results_retention_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'minimal')
        expect(config).not_to have_key('results_retention_days')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_ml_anomaly_detection_job', 'typed')
        expect(config['analysis_config']).to be_a(Hash)
        expect(config['data_description']).to be_a(Hash)
        expect(config['job_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('first', required_attrs)
        synth.elasticstack_elasticsearch_ml_anomaly_detection_job('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_ml_anomaly_detection_job')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_ml_anomaly_detection_job,
    method: :elasticstack_elasticsearch_ml_anomaly_detection_job,
    required_attrs: { analysis_config: { 'key1' => 'val1' }, data_description: { 'key1' => 'val1' }, job_id: 'test-value' },
    expected_outputs: [:id, :allow_lazy_open, :analysis_limits, :create_time, :daily_model_snapshot_retention_after_days, :job_type, :job_version, :model_snapshot_id, :model_snapshot_retention_days, :results_index_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
