# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_kibana_security_exception_list resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackKibanaSecurityExceptionList do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', name: 'test-value', type: 'test-value' } }

  describe ':elasticstack_kibana_security_exception_list' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'test')
        validate_required_attributes(config, [:description, :name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_exception_list('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_kibana_security_exception_list)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_kibana_security_exception_list('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_kibana_security_exception_list.test.id}")
        expect(ref.created_at).to eq("${elasticstack_kibana_security_exception_list.test.created_at}")
        expect(ref.created_by).to eq("${elasticstack_kibana_security_exception_list.test.created_by}")
        expect(ref.immutable).to eq("${elasticstack_kibana_security_exception_list.test.immutable}")
        expect(ref.list_id).to eq("${elasticstack_kibana_security_exception_list.test.list_id}")
        expect(ref.namespace_type).to eq("${elasticstack_kibana_security_exception_list.test.namespace_type}")
        expect(ref.space_id).to eq("${elasticstack_kibana_security_exception_list.test.space_id}")
        expect(ref.tie_breaker_id).to eq("${elasticstack_kibana_security_exception_list.test.tie_breaker_id}")
        expect(ref.updated_at).to eq("${elasticstack_kibana_security_exception_list.test.updated_at}")
        expect(ref.updated_by).to eq("${elasticstack_kibana_security_exception_list.test.updated_by}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('created_by')
        expect(config).not_to have_key('immutable')
        expect(config).not_to have_key('list_id')
        expect(config).not_to have_key('namespace_type')
        expect(config).not_to have_key('space_id')
        expect(config).not_to have_key('tie_breaker_id')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('updated_by')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ meta: 'test-value', os_types: ['test-value'], tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'full')
        expect(config).to have_key('meta')
        expect(config).to have_key('os_types')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('opt', required_attrs.merge(meta: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes os_types when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('opt', required_attrs.merge(os_types: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'opt')
        expect(config).to have_key('os_types')
      end

      it 'omits os_types when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'minimal')
        expect(config).not_to have_key('os_types')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_kibana_security_exception_list', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_kibana_security_exception_list('first', required_attrs)
        synth.elasticstack_kibana_security_exception_list('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_kibana_security_exception_list')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_kibana_security_exception_list,
    method: :elasticstack_kibana_security_exception_list,
    required_attrs: { description: 'test-value', name: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :created_at, :created_by, :immutable, :list_id, :namespace_type, :space_id, :tie_breaker_id, :updated_at, :updated_by],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
