# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_elasticsearch_security_role_mapping resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackElasticsearchSecurityRoleMapping do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', rules: 'test-value' } }

  describe ':elasticstack_elasticsearch_security_role_mapping' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'test')
        validate_required_attributes(config, [:name, :rules])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_role_mapping('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_elasticsearch_security_role_mapping)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_elasticsearch_security_role_mapping('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_elasticsearch_security_role_mapping.test.id}")
        expect(ref.enabled).to eq("${elasticstack_elasticsearch_security_role_mapping.test.enabled}")
        expect(ref.metadata).to eq("${elasticstack_elasticsearch_security_role_mapping.test.metadata}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'test')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('metadata')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ elasticsearch_connection: [{ 'key1' => 'val1' }], role_templates: 'test-value', roles: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'full')
        expect(config).to have_key('elasticsearch_connection')
        expect(config).to have_key('role_templates')
        expect(config).to have_key('roles')
      end
    end

    context 'optional attributes' do
      it 'includes elasticsearch_connection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('opt', required_attrs.merge(elasticsearch_connection: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'opt')
        expect(config).to have_key('elasticsearch_connection')
      end

      it 'omits elasticsearch_connection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'minimal')
        expect(config).not_to have_key('elasticsearch_connection')
      end
      it 'includes role_templates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('opt', required_attrs.merge(role_templates: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'opt')
        expect(config).to have_key('role_templates')
      end

      it 'omits role_templates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'minimal')
        expect(config).not_to have_key('role_templates')
      end
      it 'includes roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('opt', required_attrs.merge(roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'opt')
        expect(config).to have_key('roles')
      end

      it 'omits roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'minimal')
        expect(config).not_to have_key('roles')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_elasticsearch_security_role_mapping', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['rules']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_elasticsearch_security_role_mapping('first', required_attrs)
        synth.elasticstack_elasticsearch_security_role_mapping('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_elasticsearch_security_role_mapping')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_elasticsearch_security_role_mapping,
    method: :elasticstack_elasticsearch_security_role_mapping,
    required_attrs: { name: 'test-value', rules: 'test-value' },
    expected_outputs: [:id, :enabled, :metadata],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
