# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a elasticstack_fleet_integration_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::ElasticstackFleetIntegrationPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { integration_name: 'test-value', integration_version: 'test-value', name: 'test-value', namespace: 'test-value' } }

  describe ':elasticstack_fleet_integration_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'test')
        validate_required_attributes(config, [:integration_name, :integration_version, :name, :namespace])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_integration_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:elasticstack_fleet_integration_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.elasticstack_fleet_integration_policy('test', required_attrs)

        expect(ref.id).to eq("${elasticstack_fleet_integration_policy.test.id}")
        expect(ref.enabled).to eq("${elasticstack_fleet_integration_policy.test.enabled}")
        expect(ref.inputs).to eq("${elasticstack_fleet_integration_policy.test.inputs}")
        expect(ref.policy_id).to eq("${elasticstack_fleet_integration_policy.test.policy_id}")
        expect(ref.space_ids).to eq("${elasticstack_fleet_integration_policy.test.space_ids}")
        expect(ref.vars_json).to eq("${elasticstack_fleet_integration_policy.test.vars_json}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'test')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('inputs')
        expect(config).not_to have_key('policy_id')
        expect(config).not_to have_key('space_ids')
        expect(config).not_to have_key('vars_json')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ agent_policy_id: 'test-value', agent_policy_ids: ['test-value'], description: 'test-value', force: true, output_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'full')
        expect(config).to have_key('agent_policy_id')
        expect(config).to have_key('agent_policy_ids')
        expect(config).to have_key('description')
        expect(config).to have_key('force')
        expect(config).to have_key('output_id')
      end
    end

    context 'optional attributes' do
      it 'includes agent_policy_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('opt', required_attrs.merge(agent_policy_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'opt')
        expect(config).to have_key('agent_policy_id')
      end

      it 'omits agent_policy_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'minimal')
        expect(config).not_to have_key('agent_policy_id')
      end
      it 'includes agent_policy_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('opt', required_attrs.merge(agent_policy_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'opt')
        expect(config).to have_key('agent_policy_ids')
      end

      it 'omits agent_policy_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'minimal')
        expect(config).not_to have_key('agent_policy_ids')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes force when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('opt', required_attrs.merge(force: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'opt')
        expect(config).to have_key('force')
      end

      it 'omits force when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'minimal')
        expect(config).not_to have_key('force')
      end
      it 'includes output_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('opt', required_attrs.merge(output_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'opt')
        expect(config).to have_key('output_id')
      end

      it 'omits output_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'minimal')
        expect(config).not_to have_key('output_id')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:vars_json]
        expect(sensitive_fields).to include(:vars_json)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force: val)
          synth.elasticstack_fleet_integration_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', "bool_#{val}")
          expect(config['force']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'elasticstack_fleet_integration_policy', 'typed')
        expect(config['integration_name']).to be_a(String)
        expect(config['integration_version']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['namespace']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.elasticstack_fleet_integration_policy('first', required_attrs)
        synth.elasticstack_fleet_integration_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'elasticstack_fleet_integration_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :elasticstack_fleet_integration_policy,
    method: :elasticstack_fleet_integration_policy,
    required_attrs: { integration_name: 'test-value', integration_version: 'test-value', name: 'test-value', namespace: 'test-value' },
    expected_outputs: [:id, :enabled, :inputs, :policy_id, :space_ids, :vars_json],
    sensitive_fields: [:vars_json],
    immutable_fields: [],
    boolean_fields: [:force]
end
