# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/elasticstack_elasticsearch_security_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module ElasticstackElasticsearchSecurityUser
    include Pangea::Resources::ResourceBuilder

    define_resource :elasticstack_elasticsearch_security_user,
      attributes_class: Elasticstack::Types::ElasticsearchSecurityUserAttributes,
      outputs: { id: :id },
      map: [:roles, :username],
      map_present: [:elasticsearch_connection, :password, :password_hash, :password_wo, :password_wo_version]
  end
  module Elasticstack
    include ElasticstackElasticsearchSecurityUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Elasticstack)
