# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Elasticstack::Types
  include Dry.Types()

  class ElasticsearchSecurityUserAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Elasticstack::Types

    attribute :roles, T::Array.of(T::String)
    attribute :username, T::String
    attribute? :elasticsearch_connection, T::Array.of(T::Hash).optional
    attribute? :password, T::String.optional
    attribute? :password_hash, T::String.optional
    attribute? :password_wo, T::String.optional
    attribute? :password_wo_version, T::String.optional
  end
end
